import type { Recipe, Ingredient } from "./types"

// Helper to get current season
export function getCurrentSeason(): "hiver" | "printemps" | "été" | "automne" {
  const month = new Date().getMonth() + 1
  if (month >= 3 && month <= 5) return "printemps"
  if (month >= 6 && month <= 8) return "été"
  if (month >= 9 && month <= 11) return "automne"
  return "hiver"
}

// Helper to get current month in French
export function getCurrentMonthFr(): string {
  const months = [
    "janvier", "février", "mars", "avril", "mai", "juin",
    "juillet", "août", "septembre", "octobre", "novembre", "décembre"
  ]
  return months[new Date().getMonth()]
}

// Comprehensive Crous recipes from the official calendrier
export const mockRecipes: Recipe[] = [
  // ===============================
  // HIVER - JANVIER - Semaine 1
  // ===============================
  {
    id: "7fc3db439b57",
    nom: "Quesadillas poulet, épinards et mozzarella",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 1,
    jour: "lundi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "1 grande",
    estimatedTime: 25,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "œufs", quantity: "3", canonical: true },
      { name: "tortilla de maïs", quantity: "1", canonical: true },
      { name: "blanc de poulet", quantity: "2 tranches", canonical: true },
      { name: "mozzarella", quantity: "½", canonical: true },
      { name: "épinards crus", quantity: "1 poignée", canonical: true },
      { name: "herbes de Provence", quantity: "1 c. à c.", canonical: true },
      { name: "sauce tomate", quantity: "3 c. à s.", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à c.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Rincer les épinards.",
      "Dans un bol, battre les œufs. Saler et poivrer.",
      "Dans une poêle chaude huilée, faire cuire les œufs brouillés.",
      "Ajouter la tortilla de maïs par-dessus. Retourner la tortilla dans la poêle.",
      "Ajouter la sauce tomate, le blanc de poulet, les épinards, la mozzarella et les herbes de Provence. Laisser cuire quelques minutes jusqu'à ce que le fromage soit fondant.",
      "Replier les bords de la tortilla pour former la quesadilla et couper en triangle."
    ],
    astuce: "Le blanc de poulet sans nitrites est à privilégier.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 5,
    dietary_tags: ["protéines"],
    main_ingredients: ["poulet", "mozzarella", "épinards"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "f85e95a0b4c2",
    nom: "Blanquette végétarienne",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 1,
    jour: "mardi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 45,
    difficulty: "intermédiaire",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "haricots blancs en conserve", quantity: "1 boîte", canonical: true },
      { name: "carottes", quantity: "3", canonical: true },
      { name: "champignons de Paris frais", quantity: "1 barquette", canonical: true },
      { name: "poireau", quantity: "1", canonical: true },
      { name: "oignon", quantity: "1", canonical: true },
      { name: "œuf", quantity: "1", canonical: true },
      { name: "crème de soja", quantity: "1 c. à s.", canonical: true },
      { name: "citron", quantity: "1", canonical: true },
      { name: "farine de blé", quantity: "1 c. à s.", canonical: true },
      { name: "cumin", quantity: "1 c. à s.", canonical: true },
      { name: "huile d'olive", quantity: "2 c. à s.", canonical: true },
      { name: "riz", quantity: "8 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Préparer un roux : mélanger la farine avec de l'eau dans un bol.",
      "Éplucher et couper en dés l'oignon, le poireau, les carottes et les champignons. Les faire cuire dans une poêle huilée pendant 5 min. Ajouter un peu d'eau et laisser mijoter pendant 25 min. Extraire un peu du jus de cuisson des légumes et laisser de côté.",
      "Mélanger le roux aux légumes.",
      "Casser l'œuf et séparer le jaune du blanc dans 2 bols différents.",
      "Presser le jus de citron.",
      "Dans un saladier, ajouter la crème de soja, le jus de citron, le jaune d'œuf et le bouillon de légumes. Mélanger cette préparation aux légumes. Saler, poivrer et ajouter le cumin.",
      "Égoutter les haricots blancs et les ajouter à la préparation.",
      "Dans une casserole d'eau bouillante salée, faire cuire le riz. Servir ensemble."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 5,
    dietary_tags: ["végétarien", "légumineuses"],
    main_ingredients: ["haricots blancs", "légumes", "riz"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "1d8ef8893860",
    nom: "Tartinades de sardines et bâtonnets de carotte",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 1,
    jour: "mercredi",
    tag: "apéritif/entrée",
    categorie: "salé",
    portions: "1 personne",
    estimatedTime: 15,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "sardines en conserve", quantity: "1 petite boîte", canonical: true },
      { name: "citron", quantity: "1", canonical: true },
      { name: "pain complet ou de campagne", quantity: "2 tranches", canonical: true },
      { name: "carotte", quantity: "1", canonical: true },
      { name: "fromage blanc", quantity: "1", canonical: true },
      { name: "ciboulette fraîche", quantity: "1 c. à s.", canonical: true },
      { name: "poivre", canonical: true }
    ],
    instructions: [
      "Faire toaster les tranches de pain dans un grille-pain ou dans une poêle avec du beurre.",
      "Déposer les sardines sur les tranches de pain. Presser le jus du citron et mettre la moitié du jus sur les sardines.",
      "Laver, éplucher et couper la carotte en bâtonnets.",
      "Dans un bol, mélanger le fromage blanc, le reste du jus de citron et la ciboulette. Poivrer.",
      "Tremper les bâtonnets de carotte dans la sauce. Déguster avec les tartines de sardines."
    ],
    astuce: "Tu peux également réaliser des bâtonnets de radis noir ou de chou-fleur cru.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 5,
    dietary_tags: ["poisson", "oméga-3"],
    main_ingredients: ["sardines", "carotte", "fromage blanc"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "06ba0d5861d8",
    nom: "Flan au poireau au micro-ondes",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 1,
    jour: "jeudi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "1 personne",
    estimatedTime: 20,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "petit poireau", quantity: "1", canonical: true },
      { name: "œuf", quantity: "1", canonical: true },
      { name: "crème de soja", quantity: "5 c. à s.", canonical: true },
      { name: "curry", quantity: "1 c. à c.", canonical: true },
      { name: "beurre", quantity: "1 noisette", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à c.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Laver et couper le poireau en rondelles.",
      "Dans une casserole chaude huilée, faire cuire le poireau pendant 10 min.",
      "Pendant la cuisson, préparer le flan dans un grand bol : battre les œufs avec la crème de soja. Saler, poivrer et ajouter le curry.",
      "Lorsque le poireau est cuit, l'égoutter et l'ajouter à la préparation. Mélanger.",
      "Verser la préparation dans un plat beurré (compatible au micro-ondes).",
      "Cuire au micro-ondes pendant 5 à 6 min. Vérifier la cuisson avec un couteau."
    ],
    cuisson_micro_ondes: true,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 5,
    dietary_tags: ["végétarien"],
    main_ingredients: ["poireau", "œuf", "crème"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "c42be2391dd7",
    nom: "Pancakes salés épinards et mozzarella",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 1,
    jour: "vendredi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 20,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "épinards frais", quantity: "1 poignée", canonical: true },
      { name: "œuf", quantity: "1", canonical: true },
      { name: "farine de blé", quantity: "3 c. à s.", canonical: true },
      { name: "mozzarella", quantity: "4-5 tranches", canonical: true },
      { name: "lait", quantity: "1 petit verre", canonical: true },
      { name: "levure chimique", quantity: "½ c. à c.", canonical: true },
      { name: "huile de tournesol", quantity: "2 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Rincer les épinards et enlever éventuellement les tiges dures. Couper les feuilles en morceaux.",
      "Couper la mozzarella en dés.",
      "Dans un saladier, faire la pâte à pancake : mélanger l'œuf, la farine, le lait et la levure. Saler et poivrer. Ajouter les épinards et la mozzarella.",
      "Dans une poêle chaude huilée, à l'aide d'une cuillère à soupe, déposer des petits tas de pâte et faire cuire quelques minutes de chaque côté."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 5,
    dietary_tags: ["végétarien"],
    main_ingredients: ["épinards", "mozzarella", "farine"],
    canonical_ingredients_status: "verified"
  },
  // ===============================
  // HIVER - JANVIER - Semaine 2
  // ===============================
  {
    id: "d0c8ab48c209",
    nom: "Curry de poireau",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 2,
    jour: "lundi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 30,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "oignon", quantity: "1", canonical: true },
      { name: "poireau", quantity: "1", canonical: true },
      { name: "pommes de terre", quantity: "2", canonical: true },
      { name: "riz blanc", quantity: "10 c. à s.", canonical: true },
      { name: "crème de coco", quantity: "1 verre", canonical: true },
      { name: "curry", quantity: "2 c. à s.", canonical: true },
      { name: "huile d'olive", quantity: "2 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Rincer et découper le poireau en fines lamelles.",
      "Rincer et découper les pommes de terre en dés.",
      "Éplucher et découper l'oignon en dés.",
      "Dans une poêle chaude huilée, faire cuire l'oignon pendant 2 min.",
      "Ajouter le poireau et les pommes de terre. Laisser cuire 10 min en remuant.",
      "Ajouter la crème de coco et le curry. Laisser mijoter 15 min.",
      "Dans une casserole d'eau bouillante salée, faire cuire le riz. Servir ensemble."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 6,
    dietary_tags: ["végétarien", "vegan"],
    main_ingredients: ["poireau", "pommes de terre", "riz"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "051189324242",
    nom: "Poulet à la moutarde et purée de carottes",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 2,
    jour: "mardi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "1 personne",
    estimatedTime: 35,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "escalope de poulet", quantity: "1", canonical: true },
      { name: "farine", quantity: "1 c. à c.", canonical: true },
      { name: "lait", quantity: "1 verre", canonical: true },
      { name: "moutarde", quantity: "1 c. à c.", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à c.", canonical: true },
      { name: "carottes", quantity: "2", canonical: true },
      { name: "pomme de terre", quantity: "1", canonical: true },
      { name: "crème de coco", quantity: "1 verre", canonical: true },
      { name: "curry", quantity: "1 c. à c.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Éplucher et couper les carottes et la pomme de terre en dés.",
      "Dans une casserole d'eau bouillante salée, faire cuire les légumes jusqu'à tendreté.",
      "Les égoutter et les écraser à la fourchette. Ajouter la crème de coco. Saler, poivrer et ajouter le curry. Bien mélanger.",
      "Mettre de la farine sur chaque face de l'escalope. Tapoter pour retirer l'excédent.",
      "Dans une poêle chaude huilée, faire cuire et dorer l'escalope 4 min sur chaque face.",
      "Mélanger le lait et la moutarde. Saler et poivrer. Verser dans la poêle et laisser mijoter 15 min jusqu'à ce que la sauce épaississe."
    ],
    astuce: "Si tu as un mixeur, tu peux mixer la purée pour une texture plus homogène.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 6,
    dietary_tags: ["protéines"],
    main_ingredients: ["poulet", "carottes", "pommes de terre"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "49a2ce50abd0",
    nom: "Pâtes au thon",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 2,
    jour: "mercredi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 20,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "crème fraîche", quantity: "1 verre", canonical: true },
      { name: "oignon", quantity: "1", canonical: true },
      { name: "pâtes", quantity: "8-10 c. à s.", canonical: true },
      { name: "thon en boîte", quantity: "1 boîte", canonical: true },
      { name: "sauce tomate", quantity: "3 c. à s.", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Dans une casserole d'eau bouillante salée, faire cuire les pâtes selon le temps indiqué sur le paquet.",
      "Éplucher et couper l'oignon en dés.",
      "Dans une poêle chaude huilée, faire cuire l'oignon pendant 5 min.",
      "Ajouter la sauce tomate, la crème fraîche et le thon émietté. Bien mélanger.",
      "Égoutter les pâtes et les ajouter à la sauce."
    ],
    astuce: "Privilégie les pâtes à farine complète ou semi-complète pour faire le plein de minéraux. Elles sont aussi plus rassasiantes.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 6,
    dietary_tags: ["poisson"],
    main_ingredients: ["pâtes", "thon", "crème"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "5e0ec1f686eb",
    nom: "Velouté poireaux, pesto et fromage de chèvre",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 2,
    jour: "jeudi",
    tag: "déjeuner/dîner léger",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 35,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "poireaux", quantity: "2", canonical: true },
      { name: "pommes de terre", quantity: "2", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à s.", canonical: true },
      { name: "eau + cube de bouillon", quantity: "3 verres", canonical: true },
      { name: "pesto vert", quantity: "3 c. à s.", canonical: true },
      { name: "oignon", quantity: "1", canonical: true },
      { name: "fromage de chèvre", quantity: "1 petit", canonical: true },
      { name: "poivre", canonical: true }
    ],
    instructions: [
      "Éplucher et couper l'oignon, les poireaux et les pommes de terre en dés.",
      "Dans une casserole (à bords hauts) chaude et huilée, faire cuire l'oignon quelques minutes.",
      "Ajouter les poireaux, les pommes de terre et le bouillon.",
      "Laisser mijoter pendant 20 min en mélangeant de temps en temps.",
      "Mixer la préparation. Si tu n'as pas de mixeur, tu peux laisser les légumes entiers.",
      "Ajouter le pesto. Bien mélanger.",
      "Servir dans des bols et ajouter par-dessus le fromage de chèvre coupé en dés."
    ],
    astuce: "Les veloutés sont des recettes anti-gaspi par excellence. Tu peux ajouter des légumes abîmés pour éviter de les jeter.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 6,
    dietary_tags: ["végétarien"],
    main_ingredients: ["poireaux", "pommes de terre", "chèvre"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "1576834c00af",
    nom: "Chakchouka d'hiver",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 2,
    jour: "vendredi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "1 personne",
    estimatedTime: 25,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "pulpe de tomate", quantity: "1 petite boîte", canonical: true },
      { name: "épinards en conserve", quantity: "1 petite boîte", canonical: true },
      { name: "pois chiches", quantity: "1 petite boîte", canonical: true },
      { name: "ail", quantity: "1 gousse", canonical: true },
      { name: "oignon", quantity: "1", canonical: true },
      { name: "œufs", quantity: "2", canonical: true },
      { name: "cumin", quantity: "1 c. à c.", canonical: true },
      { name: "paprika", quantity: "1 c. à c.", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à s.", canonical: true },
      { name: "persil", quantity: "1 c. à c.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Éplucher et couper l'oignon et l'ail en dés.",
      "Dans une poêle chaude huilée, faire cuire l'oignon et l'ail pendant 3 min.",
      "Ajouter la pulpe de tomate, les épinards égouttés et les pois chiches égouttés.",
      "Ajouter le cumin et le paprika. Saler et poivrer. Laisser mijoter 10 min.",
      "Casser les œufs dans la préparation. Laisser cuire environ 5 min à feu doux avec un couvercle. Parsemer de persil."
    ],
    astuce: "Tu peux utiliser des épinards en conserve, surgelés ou frais.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 6,
    dietary_tags: ["végétarien", "légumineuses"],
    main_ingredients: ["œufs", "pois chiches", "tomate"],
    canonical_ingredients_status: "verified"
  },
  // ===============================
  // HIVER - JANVIER - Semaine 3 (Spéciale Chou-fleur)
  // ===============================
  {
    id: "762ab4963327",
    nom: "Salade de chou-fleur et truite fumée",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 3,
    jour: "lundi",
    tag: "déjeuner/dîner léger",
    categorie: "salé",
    theme_special: "chou-fleur",
    portions: "1 personne",
    estimatedTime: 20,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "truite fumée", quantity: "2 tranches", canonical: true },
      { name: "chou-fleur", quantity: "¼", canonical: true },
      { name: "huile de colza", quantity: "1 c. à s.", canonical: true },
      { name: "vinaigre", quantity: "1 c. à s.", canonical: true },
      { name: "persil", quantity: "1 c. à c.", canonical: true },
      { name: "graines (tournesol, courge, sésame)", quantity: "1 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Enlever le pied du chou-fleur à l'aide d'un couteau. Détacher les bouquets et les laver.",
      "Découper la truite fumée en petits morceaux.",
      "Réaliser la vinaigrette : mélanger l'huile, le vinaigre, le persil, le sel et le poivre.",
      "Mélanger tous les ingrédients et ajouter les graines."
    ],
    astuce: "Dans cette recette, le chou-fleur est cru. Si tu le préfères cuit, plonge-le dans une casserole d'eau bouillante salée avec du jus de citron et laisser cuire pendant 15 min.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 7,
    dietary_tags: ["poisson", "oméga-3"],
    main_ingredients: ["chou-fleur", "truite", "graines"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "2d2479c36fe5",
    nom: "Burger revisité au chou-fleur",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 3,
    jour: "mardi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    theme_special: "chou-fleur",
    portions: "2 personnes",
    estimatedTime: 40,
    difficulty: "intermédiaire",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "chou-fleur", quantity: "½", canonical: true },
      { name: "pomme de terre", quantity: "1", canonical: true },
      { name: "farine de blé", quantity: "1 c. à s.", canonical: true },
      { name: "œufs", quantity: "2", canonical: true },
      { name: "steaks hachés", quantity: "2", canonical: true },
      { name: "cheddar", quantity: "2 tranches", canonical: true },
      { name: "sauce de ton choix", canonical: true },
      { name: "beurre", quantity: "1 noisette", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Laver et couper en dés le chou-fleur et la pomme de terre.",
      "Dans une casserole d'eau bouillante salée, faire cuire les légumes pendant 15 min.",
      "Égoutter et les écraser à la fourchette dans un saladier. Ajouter les œufs et la farine. Saler et poivrer. Mélanger et former 4 galettes à la main.",
      "Dans une poêle chaude huilée, faire cuire les galettes pendant 5 min de chaque côté.",
      "Dans une autre poêle chaude beurrée, faire cuire les steaks hachés.",
      "Assembler les burgers avec la sauce et avec les galettes en guise de pain burger."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 7,
    dietary_tags: ["protéines"],
    main_ingredients: ["chou-fleur", "steak", "pomme de terre"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "df7b5c84f563",
    nom: "Riz et lentilles aux oignons",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 3,
    jour: "mercredi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "1 personne",
    estimatedTime: 25,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "riz", quantity: "1 verre", canonical: true },
      { name: "lentilles en conserve", quantity: "1 petite boîte", canonical: true },
      { name: "oignon", quantity: "1", canonical: true },
      { name: "crème", quantity: "1 petit verre", canonical: true },
      { name: "curry", quantity: "1 c. à c.", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Dans une casserole d'eau bouillante salée, faire cuire le riz selon le temps indiqué sur le paquet.",
      "Égoutter les lentilles.",
      "Éplucher et couper l'oignon en fines lamelles.",
      "Dans une poêle chaude huilée, faire cuire l'oignon pendant 5 min jusqu'à ce qu'il soit doré.",
      "Ajouter le riz cuit, les lentilles, la crème et le curry. Saler et poivrer. Laisser le mélange mijoter pendant quelques minutes."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 7,
    dietary_tags: ["végétarien", "légumineuses"],
    main_ingredients: ["riz", "lentilles", "oignon"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "d3cd5a4c553e",
    nom: "Gratin dauphinois au micro-ondes",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 3,
    jour: "jeudi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    theme_special: "chou-fleur",
    portions: "2 personnes",
    estimatedTime: 25,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "pommes de terre", quantity: "4", canonical: true },
      { name: "beurre", quantity: "1 noisette", canonical: true },
      { name: "crème fraîche liquide", quantity: "1 verre", canonical: true },
      { name: "emmental râpé", quantity: "2 c. à s.", canonical: true },
      { name: "muscade", quantity: "1 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Éplucher et couper en fines lamelles les pommes de terre.",
      "Dans une casserole chaude, ajouter la crème liquide. Saler, poivrer et ajouter la muscade. Porter à ébullition la crème.",
      "Beurrer un plat passant au micro-ondes et déposer les tranches de pommes de terre.",
      "Ajouter la crème et recouvrir de fromage râpé.",
      "Mettre le plat au micro-ondes à 750W pendant 10 min."
    ],
    cuisson_micro_ondes: true,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 7,
    dietary_tags: ["végétarien"],
    main_ingredients: ["pommes de terre", "crème", "fromage"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "f211fd85791b",
    nom: "Chou-fleur cru et tartinade de fromage frais",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 3,
    jour: "vendredi",
    tag: "apéritif/entrée",
    categorie: "salé",
    theme_special: "chou-fleur",
    portions: "1 personne",
    estimatedTime: 10,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "chou-fleur", quantity: "¼", canonical: true },
      { name: "fromage frais", quantity: "1 petit pot", canonical: true },
      { name: "ciboulette", quantity: "1 c. à c.", canonical: true },
      { name: "piment d'Espelette", quantity: "1 c. à c.", canonical: true },
      { name: "poivre", canonical: true }
    ],
    instructions: [
      "Enlever le pied du chou-fleur à l'aide d'un couteau. Détacher les bouquets et les laver minutieusement. Couper les bouquets en morceaux.",
      "Dans un bol, mélanger le fromage frais, la ciboulette et le piment d'Espelette. Poivrer.",
      "Tremper les morceaux de chou-fleur dans le fromage frais."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 7,
    dietary_tags: ["végétarien"],
    main_ingredients: ["chou-fleur", "fromage frais"],
    canonical_ingredients_status: "verified"
  },
  // ===============================
  // HIVER - JANVIER - Semaine 4
  // ===============================
  {
    id: "25541c40e102",
    nom: "Pancakes salés au thon",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 4,
    jour: "lundi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "1 personne",
    estimatedTime: 15,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "thon en boîte", quantity: "1 petite boîte", canonical: true },
      { name: "œufs", quantity: "2", canonical: true },
      { name: "farine de blé", quantity: "1 c. à s.", canonical: true },
      { name: "emmental râpé", quantity: "2 c. à s.", canonical: true },
      { name: "herbes de Provence", quantity: "1 c. à c.", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à s.", canonical: true },
      { name: "poivre", canonical: true }
    ],
    instructions: [
      "Dans un bol, ajouter le thon émietté, les œufs, la farine, l'emmental râpé, les herbes de Provence et le poivre. Bien mélanger.",
      "Dans une poêle chaude huilée, former des pancakes à l'aide d'une cuillère à soupe et faire cuire quelques minutes de chaque côté."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 8,
    dietary_tags: ["poisson"],
    main_ingredients: ["thon", "œufs", "fromage"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "231e72300b5a",
    nom: "Wok aux lentilles corail, oignons et carottes",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 4,
    jour: "mardi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 30,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "lentilles corail crues", quantity: "2 verres", canonical: true },
      { name: "nouilles de riz", quantity: "2 verres", canonical: true },
      { name: "carottes", quantity: "2", canonical: true },
      { name: "oignon", quantity: "1", canonical: true },
      { name: "ail", quantity: "1 gousse", canonical: true },
      { name: "huile de tournesol", quantity: "2 c. à s.", canonical: true },
      { name: "sauce soja", quantity: "2 c. à s.", canonical: true },
      { name: "gingembre en poudre", quantity: "1 c. à s.", canonical: true },
      { name: "coriandre", quantity: "quelques brins", canonical: true },
      { name: "poivre", canonical: true }
    ],
    instructions: [
      "Éplucher et couper en dés l'ail, l'oignon et les carottes.",
      "Dans une casserole chaude huilée, faire cuire les légumes avec les lentilles corail pendant 15 min.",
      "En parallèle, faire cuire les nouilles de riz dans une casserole d'eau bouillante selon le temps indiqué sur le paquet.",
      "Une fois que les nouilles sont cuites, les ajouter aux légumes et lentilles. Ajouter la sauce soja, le gingembre et le poivre. Bien mélanger. Ajouter les brins de coriandre en dernier."
    ],
    astuce: "Les lentilles corail font partie de la famille des légumineuses. Elles sont riches en fibres et ont la particularité de cuire plus vite que les lentilles vertes.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 8,
    dietary_tags: ["végétarien", "vegan", "légumineuses"],
    main_ingredients: ["lentilles corail", "nouilles", "carottes"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "0a83584f1431",
    nom: "Œufs à la florentine à la poêle",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 4,
    jour: "mercredi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 15,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "épinards (conserve, frais ou surgelés)", quantity: "400g", canonical: true },
      { name: "œufs", quantity: "4", canonical: true },
      { name: "crème fraîche", quantity: "1 c. à s.", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Rincer les épinards et enlever éventuellement les tiges dures (pour les épinards frais uniquement).",
      "Dans une poêle chaude huilée, ajouter les épinards et les laisser cuire 2 min.",
      "Ajouter la crème et mélanger. Casser les œufs sur les épinards. Saler et poivrer.",
      "Couvrir et laisser cuire 3 min à feu doux."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 8,
    dietary_tags: ["végétarien"],
    main_ingredients: ["œufs", "épinards", "crème"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "69156424b105",
    nom: "Gnocchis au poireau et sauce gorgonzola",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 4,
    jour: "jeudi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 20,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "gnocchis", quantity: "1 paquet", canonical: true },
      { name: "poireau", quantity: "½", canonical: true },
      { name: "oignon", quantity: "1", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à c.", canonical: true },
      { name: "gorgonzola", quantity: "1 morceau", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Laver et couper en dés l'oignon et le poireau.",
      "Dans une poêle chaude huilée, faire cuire les légumes pendant 10 min.",
      "Une fois les légumes cuits, ajouter le gorgonzola coupé en morceaux. Baisser le feu et mélanger.",
      "Dans une casserole d'eau chaude salée, faire cuire les gnocchis pendant 1 à 2 min. Ils remontent à la surface quand ils sont cuits.",
      "Ajouter les gnocchis cuits à la première préparation. Mélanger et poivrer."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 8,
    dietary_tags: ["végétarien"],
    main_ingredients: ["gnocchis", "poireau", "gorgonzola"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "840624256064",
    nom: "Rouleaux de jambon et poireau",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    semaine: 4,
    jour: "vendredi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "1 personne",
    estimatedTime: 25,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "poireau", quantity: "½", canonical: true },
      { name: "jambon blanc", quantity: "2 tranches", canonical: true },
      { name: "emmental râpé", quantity: "2 c. à s.", canonical: true },
      { name: "crème fraîche", quantity: "2 c. à s.", canonical: true },
      { name: "muscade", quantity: "1 c. à c.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Laver le demi-poireau et le couper en deux.",
      "Dans une casserole d'eau bouillante salée, faire cuire les 2 tronçons de poireau pendant 10 à 15 min.",
      "Égoutter les tronçons de poireau et enlever l'eau restante en les essorant à l'aide d'un torchon propre.",
      "Enrouler les tronçons de poireau avec une tranche de jambon.",
      "Les placer dans un plat passant au micro-ondes. Ajouter la crème et la muscade dans le plat. Saler et poivrer.",
      "Saupoudrer la préparation d'emmental râpé et faire cuire au micro-ondes pendant 5 min."
    ],
    astuce: "Tu peux choisir du jambon sans nitrites et sans conservateurs, qui est meilleur pour la santé.",
    cuisson_micro_ondes: true,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 8,
    dietary_tags: ["protéines"],
    main_ingredients: ["jambon", "poireau", "fromage"],
    canonical_ingredients_status: "verified"
  },
  // ===============================
  // HIVER - JANVIER - DESSERTS
  // ===============================
  {
    id: "009125325466",
    nom: "Clémentines rôties à la cannelle",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    tag: "dessert",
    categorie: "sucré",
    portions: "2 personnes",
    estimatedTime: 15,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "clémentines", quantity: "2", canonical: true },
      { name: "jus d'orange", quantity: "1 petit verre", canonical: true },
      { name: "beurre", quantity: "1 noisette", canonical: true },
      { name: "cannelle en poudre", quantity: "1 c. à s.", canonical: true }
    ],
    instructions: [
      "Éplucher les clémentines et les séparer en quartiers.",
      "Dans une poêle, faire fondre le beurre et ajouter les clémentines. Laisser dorer pendant 5 min.",
      "Ajouter le jus d'orange et la cannelle. Baisser le feu. Laisser mijoter quelques minutes avant de servir."
    ],
    astuce: "Tu peux ajouter les épices de ton choix dans ce dessert (clou de girofle, mélange 4 épices…).",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 9,
    dietary_tags: ["végétarien", "fruit"],
    main_ingredients: ["clémentines", "cannelle"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "7fea5309a031",
    nom: "Fudge au chocolat sans cuisson",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    tag: "dessert",
    categorie: "sucré",
    portions: "2 personnes",
    estimatedTime: 15,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "compotes de pommes sans sucres ajoutés", quantity: "2", canonical: true },
      { name: "chocolat de ton choix", quantity: "¾ tablette", canonical: true },
      { name: "fruits secs (amandes, pistaches, noix)", quantity: "quelques", canonical: true }
    ],
    instructions: [
      "Faire fondre le chocolat au micro-ondes ou au bain-marie (placer le chocolat dans un récipient au-dessus d'une casserole d'eau bouillante).",
      "Dans un saladier, mélanger la compote et le chocolat fondu.",
      "Laisser figer au réfrigérateur pendant 4 h.",
      "Servir avec quelques fruits secs concassés par-dessus."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 9,
    dietary_tags: ["végétarien"],
    main_ingredients: ["chocolat", "compote"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "35bf373ae8c3",
    nom: "Mug cake à la vanille",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    tag: "dessert",
    categorie: "sucré",
    portions: "1 personne",
    estimatedTime: 5,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "extrait de vanille liquide", quantity: "1 c. à c.", canonical: true },
      { name: "farine", quantity: "1 c. à s. bombée", canonical: true },
      { name: "levure chimique", quantity: "½ c. à c.", canonical: true },
      { name: "sucre", quantity: "1 c. à c.", canonical: true },
      { name: "beurre", quantity: "15g", canonical: true },
      { name: "œuf", quantity: "1", canonical: true }
    ],
    instructions: [
      "Dans un mug, faire fondre le beurre 30 sec au micro-ondes.",
      "Ajouter le sucre et l'œuf entier. Mélanger.",
      "Incorporer la farine et la levure chimique. Bien mélanger pour éviter les grumeaux.",
      "Ajouter l'extrait de vanille liquide.",
      "Faire cuire au micro-ondes pendant 50 sec. Vérifier la cuisson."
    ],
    cuisson_micro_ondes: true,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 9,
    dietary_tags: ["végétarien"],
    main_ingredients: ["vanille", "farine", "œuf"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "2e8855a86ddf",
    nom: "Pomme au chocolat à la poêle",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    tag: "dessert",
    categorie: "sucré",
    portions: "1 personne",
    estimatedTime: 10,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "pomme", quantity: "1", canonical: true },
      { name: "beurre", quantity: "1 noisette", canonical: true },
      { name: "chocolat noir ou au lait", quantity: "quelques carreaux", canonical: true }
    ],
    instructions: [
      "Éplucher et couper la pomme en rondelles.",
      "Dans une poêle chaude beurrée, faire dorer les rondelles de pomme pendant 5 min sur feu doux.",
      "Ajouter quelques carreaux de chocolat et laisser fondre."
    ],
    astuce: "Tu peux réaliser cette recette avec n'importe quel fruit de saison (orange, banane, poire…).",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 9,
    dietary_tags: ["végétarien", "fruit"],
    main_ingredients: ["pomme", "chocolat"],
    canonical_ingredients_status: "verified"
  },
  // ===============================
  // HIVER - FÉVRIER - Semaine 1
  // ===============================
  {
    id: "b3bd782013ca",
    nom: "Soupe de pois cassés",
    saison: "hiver",
    mois: "février",
    mois_numero: 2,
    semaine: 1,
    jour: "lundi",
    tag: "déjeuner/dîner léger",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 50,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "pois cassés secs", quantity: "10 c. à s.", canonical: true },
      { name: "oignon", quantity: "½", canonical: true },
      { name: "ail", quantity: "1 gousse", canonical: true },
      { name: "huile de tournesol", quantity: "2 c. à s.", canonical: true },
      { name: "crème", quantity: "1 petit verre", canonical: true },
      { name: "persil", quantity: "1 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Laver les pois cassés et les laisser tremper 1h dans l'eau chaude.",
      "Les égoutter. Dans une casserole d'eau bouillante, ajouter les pois cassés et les faire cuire pendant 30 min.",
      "Pendant ce temps, éplucher, laver et couper en dés l'oignon et l'ail.",
      "Dans une poêle chaude huilée, faire cuire pendant 5 à 6 min l'oignon et l'ail.",
      "Ajouter les pois cassés cuits. Ajouter le persil et la crème. Saler et poivrer. Laisser mijoter encore 5 min."
    ],
    astuce: "Passe le tout au mixeur si tu en as un. C'est une soupe économique qui se conserve facilement dans des récipients hermétiques.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 12,
    dietary_tags: ["végétarien", "vegan", "légumineuses"],
    main_ingredients: ["pois cassés", "oignon", "crème"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "21d1ed16a2ec",
    nom: "Salade de betterave, riz et fromage",
    saison: "hiver",
    mois: "février",
    mois_numero: 2,
    semaine: 1,
    jour: "mardi",
    tag: "déjeuner/dîner léger",
    categorie: "salé",
    portions: "1 personne",
    estimatedTime: 20,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "betterave cuite", quantity: "1 petite", canonical: true },
      { name: "riz", quantity: "3 c. à s.", canonical: true },
      { name: "emmental", quantity: "quelques dés", canonical: true },
      { name: "huile d'olive", quantity: "1 c. à s.", canonical: true },
      { name: "vinaigre", quantity: "1 c. à s.", canonical: true },
      { name: "persil", quantity: "1 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Cuire le riz dans une casserole d'eau bouillante salée selon le temps indiqué sur le paquet. L'égoutter et le passer sous l'eau froide dès qu'il est cuit.",
      "Découper en dés la betterave et l'emmental.",
      "Préparer la vinaigrette : mélanger l'huile, le vinaigre et le persil. Saler et poivrer.",
      "Mélanger tous les ingrédients."
    ],
    astuce: "Tu peux ajouter une tranche de jambon ou de blanc de poulet (à privilégier sans nitrites) pour compléter cette salade.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 12,
    dietary_tags: ["végétarien"],
    main_ingredients: ["betterave", "riz", "emmental"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "94568f0f6ff4",
    nom: "Filets de poulet au curry et légumes croquants",
    saison: "hiver",
    mois: "février",
    mois_numero: 2,
    semaine: 1,
    jour: "mercredi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 35,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "filets de poulet", quantity: "2", canonical: true },
      { name: "lait de coco ou crème", quantity: "1 verre", canonical: true },
      { name: "petits pois en conserve", quantity: "1 petite boîte", canonical: true },
      { name: "carotte", quantity: "1", canonical: true },
      { name: "navet", quantity: "1", canonical: true },
      { name: "poireau", quantity: "½", canonical: true },
      { name: "oignon", quantity: "½", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à s.", canonical: true },
      { name: "curry", quantity: "1 c. à c.", canonical: true },
      { name: "riz", quantity: "9 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Cuire le riz dans une casserole d'eau bouillante salée selon le temps indiqué sur le paquet.",
      "Découper le poulet en fines lamelles.",
      "Éplucher, laver et couper la carotte, le navet, le poireau et l'oignon en dés.",
      "Dans une poêle chaude huilée, faire cuire le poulet pendant 5 min.",
      "Enlever la viande, ajouter les légumes dans la poêle et les faire cuire pendant 5 min. Ajouter de l'eau si le mélange accroche.",
      "Ajouter le poulet, le curry, le lait de coco et les petits pois. Laisser mijoter à feu doux pendant 5 à 6 min. Servir avec le riz."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 12,
    dietary_tags: ["protéines"],
    main_ingredients: ["poulet", "curry", "légumes"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "f9ff50444e62",
    nom: "Omelette au poireau",
    saison: "hiver",
    mois: "février",
    mois_numero: 2,
    semaine: 1,
    jour: "jeudi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 20,
    difficulty: "très facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "œufs", quantity: "5", canonical: true },
      { name: "poireau", quantity: "½", canonical: true },
      { name: "ail", quantity: "1 gousse", canonical: true },
      { name: "huile de tournesol", quantity: "1 c. à s.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Laver et couper en dés le poireau et l'ail.",
      "Dans une poêle chaude huilée, faire cuire pendant 10 à 12 min l'ail et le poireau.",
      "Casser et battre les œufs dans un bol. Saler et poivrer.",
      "Une fois que les légumes sont cuits, ajouter les œufs par-dessus.",
      "Laisser cuire pendant 3 à 4 min."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 12,
    dietary_tags: ["végétarien"],
    main_ingredients: ["œufs", "poireau"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "e279e47b560f",
    nom: "Pizza sans four",
    saison: "hiver",
    mois: "février",
    mois_numero: 2,
    semaine: 2,
    jour: "mardi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "1 pizza",
    estimatedTime: 40,
    difficulty: "intermédiaire",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "lait", quantity: "9 c. à s.", canonical: true },
      { name: "huile d'olive", quantity: "9 c. à s.", canonical: true },
      { name: "farine de blé", quantity: "8 c. à s.", canonical: true },
      { name: "œufs", quantity: "2", canonical: true },
      { name: "levure chimique", quantity: "1 sachet", canonical: true },
      { name: "thon en conserve", quantity: "1 petite boîte", canonical: true },
      { name: "coulis de tomate", quantity: "200 ml", canonical: true },
      { name: "fromage râpé", quantity: "3 c. à s.", canonical: true },
      { name: "ail", quantity: "1 gousse", canonical: true },
      { name: "oignon", quantity: "1", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Dans un saladier, mélanger le lait, l'huile et les œufs.",
      "Ajouter la farine et la levure. Laisser reposer la pâte 1h. Saler et poivrer.",
      "Couper l'oignon et l'ail en dés.",
      "Dans une poêle chaude huilée, faire cuire l'oignon et l'ail avec le coulis de tomate et le thon émietté.",
      "Dans une autre poêle chaude huilée, déposer et aplatir la pâte. Ajouter la garniture et le fromage râpé.",
      "Recouvrir la poêle avec du papier d'aluminium (ou un couvercle) et laisser cuire à feu très doux pendant 20 min."
    ],
    astuce: "Accompagne la pizza avec une salade de carottes râpées.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 13,
    dietary_tags: ["poisson"],
    main_ingredients: ["pâte", "thon", "tomate"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "f5a78e338330",
    nom: "Chili sin carne",
    saison: "hiver",
    mois: "février",
    mois_numero: 2,
    semaine: 2,
    jour: "mercredi",
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "1 personne",
    estimatedTime: 30,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "oignon", quantity: "½", canonical: true },
      { name: "ail", quantity: "1 gousse", canonical: true },
      { name: "tomates pelées", quantity: "1 boîte", canonical: true },
      { name: "haricots rouges", quantity: "1 petite boîte", canonical: true },
      { name: "riz", quantity: "4 c. à s.", canonical: true },
      { name: "huile d'olive", quantity: "1 c. à s.", canonical: true },
      { name: "cumin", quantity: "1 c. à c.", canonical: true },
      { name: "paprika", quantity: "1 c. à c.", canonical: true },
      { name: "coriandre", quantity: "1 c. à c.", canonical: true },
      { name: "origan", quantity: "1 c. à c.", canonical: true },
      { name: "sel et poivre", canonical: true }
    ],
    instructions: [
      "Dans une casserole d'eau bouillante salée, faire cuire le riz selon le temps indiqué.",
      "Éplucher, laver et couper en dés l'oignon et l'ail.",
      "Dans une poêle chaude huilée, faire cuire pendant 3 min l'oignon et l'ail.",
      "Ajouter les haricots rouges égouttés, les tomates pelées, le cumin, le paprika, la coriandre et l'origan. Saler et Poivrer. Laisser mijoter pendant 10 min à feu doux. Servir avec le riz cuit."
    ],
    astuce: "Si tu utilises des herbes fraîches, il est préférable de les ajouter vers la fin de cuisson. Elles peuvent perdre leur saveur si elles sont trop cuites.",
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "crous",
    source_pdf: "Crous_CalendrierRecette_Hiver.pdf",
    source_page: 13,
    dietary_tags: ["végétarien", "vegan", "légumineuses"],
    main_ingredients: ["haricots rouges", "tomates", "riz"],
    canonical_ingredients_status: "verified"
  },
  // ===============================
  // SUGGESTIONS LUMORA (IA)
  // ===============================
  {
    id: "lumora001",
    nom: "Buddha bowl d'hiver aux légumes rôtis",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 40,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "patate douce", quantity: "1", canonical: true },
      { name: "pois chiches en conserve", quantity: "1 boîte", canonical: true },
      { name: "quinoa", quantity: "150g", canonical: true },
      { name: "chou kale", quantity: "100g", canonical: true },
      { name: "avocat", quantity: "1", canonical: true },
      { name: "sauce tahini", quantity: "3 c. à s.", canonical: true },
      { name: "citron", quantity: "1", canonical: true },
      { name: "huile d'olive", quantity: "2 c. à s.", canonical: true },
      { name: "cumin", quantity: "1 c. à c.", canonical: true }
    ],
    instructions: [
      "Préchauffer le four à 200°C.",
      "Couper la patate douce en cubes. Les disposer sur une plaque avec les pois chiches égouttés. Arroser d'huile et saupoudrer de cumin.",
      "Enfourner 25 min jusqu'à ce que les légumes soient dorés.",
      "Pendant ce temps, cuire le quinoa selon les instructions du paquet.",
      "Masser le chou kale avec un filet d'huile d'olive et le jus de citron.",
      "Assembler les bols : quinoa, légumes rôtis, kale, avocat en tranches.",
      "Arroser de sauce tahini et servir."
    ],
    astuce: "Tu peux préparer les légumes rôtis à l'avance et les réchauffer au moment de servir.",
    cuisson_micro_ondes: false,
    sans_four: false,
    source: "lumora",
    dietary_tags: ["végétarien", "vegan", "légumineuses"],
    main_ingredients: ["patate douce", "pois chiches", "quinoa"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "lumora002",
    nom: "Nouilles sautées aux légumes d'hiver",
    saison: "hiver",
    mois: "février",
    mois_numero: 2,
    tag: "déjeuner/dîner",
    categorie: "salé",
    portions: "2 personnes",
    estimatedTime: 25,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "nouilles de blé", quantity: "200g", canonical: true },
      { name: "chou chinois", quantity: "200g", canonical: true },
      { name: "carottes", quantity: "2", canonical: true },
      { name: "champignons shiitake", quantity: "150g", canonical: true },
      { name: "ail", quantity: "2 gousses", canonical: true },
      { name: "gingembre frais", quantity: "2 cm", canonical: true },
      { name: "sauce soja", quantity: "3 c. à s.", canonical: true },
      { name: "huile de sésame", quantity: "1 c. à s.", canonical: true },
      { name: "graines de sésame", quantity: "1 c. à s.", canonical: true }
    ],
    instructions: [
      "Cuire les nouilles selon les instructions du paquet. Les égoutter.",
      "Émincer le chou chinois, râper les carottes, trancher les champignons.",
      "Hacher finement l'ail et le gingembre.",
      "Dans un wok chaud avec l'huile, faire sauter l'ail et le gingembre 30 sec.",
      "Ajouter les légumes et cuire 5 min à feu vif en remuant.",
      "Incorporer les nouilles et la sauce soja. Mélanger 2 min.",
      "Servir avec l'huile de sésame et les graines de sésame."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "lumora",
    dietary_tags: ["végétarien", "vegan"],
    main_ingredients: ["nouilles", "chou chinois", "champignons"],
    canonical_ingredients_status: "verified"
  },
  // ===============================
  // DESSERTS LUMORA
  // ===============================
  {
    id: "lumora-dessert001",
    nom: "Crumble aux poires et cannelle",
    saison: "hiver",
    mois: "janvier",
    mois_numero: 1,
    tag: "dessert",
    categorie: "sucré",
    portions: "4 personnes",
    estimatedTime: 35,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "poires", quantity: "4", canonical: true },
      { name: "farine", quantity: "100g", canonical: true },
      { name: "beurre froid", quantity: "80g", canonical: true },
      { name: "sucre roux", quantity: "80g", canonical: true },
      { name: "flocons d'avoine", quantity: "30g", canonical: true },
      { name: "cannelle", quantity: "1 c. à c.", canonical: true }
    ],
    instructions: [
      "Préchauffer le four à 180°C.",
      "Éplucher et couper les poires en cubes. Les disposer dans un plat à gratin.",
      "Saupoudrer de cannelle.",
      "Dans un saladier, mélanger la farine, le sucre et les flocons d'avoine.",
      "Ajouter le beurre froid coupé en dés. Sabler du bout des doigts jusqu'à obtenir une texture grumeleuse.",
      "Répartir le crumble sur les poires.",
      "Enfourner 25-30 min jusqu'à ce que le dessus soit doré."
    ],
    astuce: "Sers tiède avec une boule de glace à la vanille ou de la crème fraîche.",
    cuisson_micro_ondes: false,
    sans_four: false,
    source: "lumora",
    dietary_tags: ["végétarien", "fruit"],
    main_ingredients: ["poires", "farine", "beurre"],
    canonical_ingredients_status: "verified"
  },
  {
    id: "lumora-dessert002",
    nom: "Riz au lait à la fleur d'oranger",
    saison: "hiver",
    mois: "février",
    mois_numero: 2,
    tag: "dessert",
    categorie: "sucré",
    portions: "4 personnes",
    estimatedTime: 45,
    difficulty: "facile",
    imageUrl: "/placeholder-recipe.jpg",
    ingredients: [
      { name: "riz rond", quantity: "150g", canonical: true },
      { name: "lait entier", quantity: "1L", canonical: true },
      { name: "sucre", quantity: "80g", canonical: true },
      { name: "eau de fleur d'oranger", quantity: "2 c. à s.", canonical: true },
      { name: "gousse de vanille", quantity: "1", canonical: true },
      { name: "cannelle", quantity: "pour saupoudrer", canonical: true }
    ],
    instructions: [
      "Faire bouillir une grande casserole d'eau. Y plonger le riz 2 min puis l'égoutter.",
      "Dans une casserole, porter le lait à ébullition avec la gousse de vanille fendue.",
      "Ajouter le riz et baisser le feu. Cuire 30-35 min en remuant régulièrement.",
      "Incorporer le sucre et l'eau de fleur d'oranger.",
      "Répartir dans des ramequins.",
      "Servir tiède ou froid, saupoudré de cannelle."
    ],
    cuisson_micro_ondes: false,
    sans_four: true,
    source: "lumora",
    dietary_tags: ["végétarien"],
    main_ingredients: ["riz", "lait", "fleur d'oranger"],
    canonical_ingredients_status: "verified"
  }
]

// Helper function to get recipes by season
export function getRecipesBySeason(season: "hiver" | "printemps" | "été" | "automne"): Recipe[] {
  return mockRecipes.filter(r => r.saison === season)
}

// Helper function to get seasonal recipes for current time
export function getSeasonalRecipes(): Recipe[] {
  const currentSeason = getCurrentSeason()
  return getRecipesBySeason(currentSeason)
}

// Helper function to get desserts
export function getDesserts(): Recipe[] {
  return mockRecipes.filter(r => r.tag === "dessert" || r.categorie === "sucré")
}

// Helper function to get main dishes
export function getMainDishes(): Recipe[] {
  return mockRecipes.filter(r => r.tag.includes("déjeuner") || r.tag.includes("dîner"))
}

// Shuffle recipes for swipe deck with seasonal priority
export function getShuffledRecipesForSwipe(): Recipe[] {
  const currentSeason = getCurrentSeason()
  const seasonalRecipes = mockRecipes.filter(r => r.saison === currentSeason)
  
  // Shuffle seasonal recipes
  const shuffled = [...seasonalRecipes].sort(() => Math.random() - 0.5)
  
  return shuffled
}
