-- City Café batch 01: quiches et tartes. Generated from city-cafe-recipes-batch-01.json.
BEGIN;

INSERT INTO public.ingredients (name, category, aliases)
VALUES
  ('Pâte brisée', 'Féculents, pains et céréales', '{}'::text[]),
  ('Thon', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Saumon fumé', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Œufs', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Crème', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Lait', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Ciboulette', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Moutarde', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Poivre', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Fromage frais', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Curry', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Citrons', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Tomates', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Chorizo', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Feta', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Origan', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Huile', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Poulet', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Estragon', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Patates douces', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Lardons', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Thym', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Pepperoni', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Butternut', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Sauge', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Pommes de terre', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Reblochon', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Miel', 'Épicerie, condiments et produits sucrés', '{}'::text[])
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.recipes (id, nom, description, saison, mois, mois_numero, semaine, jour, tag, categorie, theme_special, portions, estimated_time, difficulty, image_url, ingredients, instructions, astuce, cuisson_micro_ondes, sans_four, source, source_pdf, source_page, dietary_tags, main_ingredients, equipment, canonical_ingredients_status)
VALUES
  ('city-cafe-quiche-thon-saumon-fume', 'Quiche au thon et saumon fumé', 'Une quiche fondante où le thon émietté et le saumon fumé apportent une garniture iodée, liée par un appareil léger à la crème.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 55, 'facile', 'https://images.pexels.com/photos/10687590/pexels-photo-10687590.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte brisée","quantity":"1","unit":"rouleau","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Thon","quantity":"140","unit":"g égoutté","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Saumon fumé","quantity":"100","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Œufs","quantity":"3","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"20","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Lait","quantity":"10","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Ciboulette","quantity":"10","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Moutarde","quantity":"1","unit":"c. à café","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Poivre","quantity":"1","unit":"pincée","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préchauffer le four à 180 °C. Foncer un moule de 26 cm avec la pâte, piquer le fond et le badigeonner de moutarde.","Égoutter le thon et l’émietter. Couper le saumon fumé en lanières, puis répartir les deux poissons sur le fond de tarte.","Fouetter les œufs avec la crème et le lait. Ajouter la ciboulette ciselée et poivrer; saler très légèrement car le saumon est déjà salé.","Verser l’appareil dans le moule sans recouvrir complètement les morceaux de saumon.","Enfourner 35 à 40 minutes, jusqu’à ce que le centre soit pris et le dessus doré. Laisser reposer 10 minutes avant de couper."]'::jsonb, 'Pour une pâte plus croustillante, précuire le fond garni de papier cuisson et de poids pendant 10 minutes.', false, false, 'broco-chou', null, null, array['poisson']::text[], array['thon', 'saumon fumé', 'œufs']::text[], array['four', 'moule à tarte', 'saladier', 'fouet']::text[], 'verified'),
  ('city-cafe-quiche-thon-curry-fromage-frais', 'Quiche au thon, curry et fromage frais', 'Le thon et le curry doux s’associent à du fromage frais dans une quiche crémeuse, relevée d’une pointe de citron.', 'hiver', 'février', 2, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 55, 'facile', 'https://images.pexels.com/photos/5419293/pexels-photo-5419293.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte brisée","quantity":"1","unit":"rouleau","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Thon","quantity":"180","unit":"g égoutté","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Fromage frais","quantity":"150","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Œufs","quantity":"3","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"15","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Curry","quantity":"2","unit":"c. à café","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Citrons","quantity":"0.5","unit":"pièce","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Poivre","quantity":"1","unit":"pincée","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préchauffer le four à 180 °C et foncer un moule à tarte avec la pâte. Piquer le fond.","Égoutter le thon, l’émietter et le répartir sur la pâte.","Détendre le fromage frais avec la crème. Incorporer les œufs un à un, le curry, le zeste finement râpé et une cuillère à café de jus de citron.","Poivrer, verser l’appareil sur le thon et lisser la surface.","Cuire 35 à 40 minutes, jusqu’à ce que la garniture soit prise et le bord bien doré. Attendre 10 minutes avant de servir."]'::jsonb, 'Le fromage frais nature remplace le cream cheese; si le thon est déjà salé, goûter l’appareil avant d’ajouter du sel.', false, false, 'broco-chou', null, null, array['poisson']::text[], array['thon', 'fromage frais', 'curry']::text[], array['four', 'moule à tarte', 'saladier', 'fouet']::text[], 'verified'),
  ('city-cafe-quiche-tomate-chorizo-feta', 'Quiche à la tomate, au chorizo et à la feta', 'Une quiche estivale aux tomates juteuses, chorizo légèrement épicé et feta salée.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 60, 'facile', 'https://images.pexels.com/photos/5419175/pexels-photo-5419175.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte brisée","quantity":"1","unit":"rouleau","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Tomates","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Chorizo","quantity":"100","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Feta","quantity":"120","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Œufs","quantity":"3","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"20","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Origan","quantity":"1","unit":"c. à café","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Huile","quantity":"1","unit":"c. à café","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préchauffer le four à 180 °C. Couper les tomates en rondelles et les déposer sur du papier absorbant 10 minutes.","Foncer un moule avec la pâte et piquer le fond. Couper le chorizo en demi-rondelles et le faire revenir 2 minutes à sec; égoutter le gras.","Fouetter les œufs avec la crème et l’origan. Émietter la feta.","Répartir le chorizo et les tomates sur la pâte, puis verser l’appareil et parsemer de feta.","Enfourner 40 à 45 minutes, jusqu’à ce que la quiche soit dorée et prise au centre. Reposer 10 minutes avant de servir."]'::jsonb, 'Des tomates bien égouttées évitent de détremper le fond; le chorizo doux convient si l’on préfère limiter le piquant.', false, false, 'broco-chou', null, null, '{}'::text[], array['tomates', 'chorizo', 'feta']::text[], array['four', 'moule à tarte', 'poêle', 'saladier']::text[], 'verified'),
  ('city-cafe-quiche-poulet-tomate-estragon', 'Quiche au poulet, à la tomate et à l’estragon', 'Des morceaux de poulet, de la tomate et de l’estragon frais dans un appareil crémeux, cuits sur une pâte dorée.', 'été', 'juin', 6, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 60, 'facile', 'https://images.pexels.com/photos/10885316/pexels-photo-10885316.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte brisée","quantity":"1","unit":"rouleau","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Poulet","quantity":"250","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Tomates","quantity":"200","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"3","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"20","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Estragon","quantity":"8","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Huile","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Poivre","quantity":"1","unit":"pincée","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préchauffer le four à 180 °C. Foncer un moule avec la pâte et piquer le fond.","Couper le poulet en dés. Le saisir dans l’huile 5 à 6 minutes jusqu’à cuisson complète; laisser tiédir.","Couper les tomates en dés et les éponger. Fouetter les œufs avec la crème, l’estragon ciselé et le poivre.","Répartir le poulet et la tomate sur la pâte, puis verser l’appareil.","Cuire 40 à 45 minutes, jusqu’à ce que le centre soit pris. Laisser reposer 10 minutes avant de démouler."]'::jsonb, 'L’estragon séché peut dépanner: en utiliser environ une cuillère à café et l’incorporer à l’appareil quelques minutes avant cuisson.', false, false, 'broco-chou', null, null, array['volaille']::text[], array['poulet', 'tomates', 'estragon']::text[], array['four', 'moule à tarte', 'poêle', 'saladier']::text[], 'verified'),
  ('city-cafe-quiche-lardons-patate-douce', 'Quiche aux lardons et à la patate douce', 'La patate douce rôtie apporte une note douce aux lardons fumés dans cette quiche familiale.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 65, 'facile', 'https://images.pexels.com/photos/288264/pexels-photo-288264.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte brisée","quantity":"1","unit":"rouleau","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Patates douces","quantity":"350","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Lardons","quantity":"120","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Œufs","quantity":"3","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"20","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Thym","quantity":"1","unit":"c. à café","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Huile","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préchauffer le four à 200 °C. Peler la patate douce, la couper en dés de 1,5 cm, mélanger avec l’huile et le thym, puis rôtir 20 minutes.","Baisser le four à 180 °C. Foncer un moule avec la pâte et piquer le fond.","Faire dorer les lardons 4 minutes dans une poêle, puis les égoutter. Fouetter les œufs avec la crème.","Répartir les dés de patate douce et les lardons sur la pâte; verser l’appareil.","Cuire 35 à 40 minutes, jusqu’à ce que le dessus soit doré et le centre pris. Laisser reposer 10 minutes."]'::jsonb, 'La patate douce peut être rôtie la veille et conservée au frais dans une boîte hermétique.', false, false, 'broco-chou', null, null, array['porc']::text[], array['lardons', 'patates douces', 'œufs']::text[], array['four', 'moule à tarte', 'poêle', 'plaque de cuisson']::text[], 'verified'),
  ('city-cafe-quiche-poulet-pepperoni-feta', 'Quiche au poulet, pepperoni et feta', 'Une quiche généreuse mêlant poulet tendre, pepperoni épicé et feta émiettée.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 55, 'facile', 'https://images.pexels.com/photos/5419305/pexels-photo-5419305.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte brisée","quantity":"1","unit":"rouleau","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Poulet","quantity":"180","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Pepperoni","quantity":"80","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Feta","quantity":"100","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Œufs","quantity":"3","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"20","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Origan","quantity":"1","unit":"c. à café","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préchauffer le four à 180 °C et foncer un moule avec la pâte. Piquer le fond.","Couper le poulet en petits dés et le cuire dans une poêle chaude 6 minutes, jusqu’à cuisson complète. Laisser tiédir.","Couper le pepperoni en fines rondelles. Fouetter les œufs et la crème avec l’origan; émietter la feta.","Répartir poulet et pepperoni dans le fond de tarte, verser l’appareil et parsemer de feta.","Cuire 35 à 40 minutes, jusqu’à ce que la quiche soit dorée et ferme au centre. Reposer 10 minutes avant de servir."]'::jsonb, 'Le pepperoni étant déjà salé et épicé, goûter la garniture avant d’ajouter du sel ou du poivre.', false, false, 'broco-chou', null, null, array['volaille']::text[], array['poulet', 'pepperoni', 'feta']::text[], array['four', 'moule à tarte', 'poêle', 'saladier']::text[], 'partial'),
  ('city-cafe-quiche-premieres-courges', 'Quiche aux premières courges', 'Une quiche de début d’automne aux courges rôties, crème et herbes fraîches.', 'automne', 'septembre', 9, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 65, 'facile', 'https://images.pexels.com/photos/5852263/pexels-photo-5852263.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte brisée","quantity":"1","unit":"rouleau","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Butternut","quantity":"400","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"3","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"20","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Feta","quantity":"80","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sauge","quantity":"6","unit":"feuilles","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Huile","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préchauffer le four à 200 °C. Peler et couper la courge en dés de 2 cm, mélanger avec l’huile et rôtir 20 minutes.","Baisser le four à 180 °C. Foncer un moule avec la pâte et piquer le fond.","Fouetter les œufs avec la crème et la sauge finement ciselée. Émietter la feta.","Répartir la courge rôtie sur la pâte, verser l’appareil et parsemer de feta.","Cuire 35 à 40 minutes, jusqu’à ce que le centre soit pris. Laisser reposer 10 minutes avant de servir."]'::jsonb, 'Une courge déjà cuite peut être utilisée: l’égoutter et réduire alors la cuisson au four de 5 minutes.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['courge', 'feta', 'sauge']::text[], array['four', 'moule à tarte', 'plaque de cuisson', 'saladier']::text[], 'partial'),
  ('city-cafe-quiche-reblochon-courge-pomme-terre', 'Quiche au reblochon, à la courge et aux pommes de terre', 'La courge et la pomme de terre rendent cette quiche automnale nourrissante, tandis que le reblochon fond en une garniture savoureuse.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 70, 'facile', 'https://images.pexels.com/photos/5852250/pexels-photo-5852250.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte brisée","quantity":"1","unit":"rouleau","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Butternut","quantity":"250","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Pommes de terre","quantity":"200","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Reblochon","quantity":"180","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"15","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Thym","quantity":"1","unit":"c. à café","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préchauffer le four à 200 °C. Peler la courge et les pommes de terre, couper en petits dés et cuire à la vapeur 10 à 12 minutes, jusqu’à ce qu’ils soient presque tendres.","Baisser le four à 180 °C. Foncer un moule avec la pâte et piquer le fond.","Fouetter les œufs avec la crème et le thym. Couper le reblochon en tranches en gardant la croûte.","Étaler courge et pommes de terre sur la pâte, verser l’appareil et disposer le reblochon dessus.","Cuire 40 à 45 minutes, jusqu’à ce que le fromage soit fondu et la quiche prise. Reposer 10 minutes avant de servir."]'::jsonb, 'Le reblochon est salé et généreux: ne salez l’appareil qu’après l’avoir goûté.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['reblochon', 'courge', 'pommes de terre']::text[], array['four', 'moule à tarte', 'casserole vapeur', 'saladier']::text[], 'partial'),
  ('city-cafe-tarte-patate-douce-feta-sauge', 'Tarte à la patate douce, à la feta et à la sauge', 'Une tarte rustique à la patate douce rôtie, feta salée et sauge parfumée.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 60, 'facile', 'https://images.pexels.com/photos/10821333/pexels-photo-10821333.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte brisée","quantity":"1","unit":"rouleau","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Patates douces","quantity":"500","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Feta","quantity":"120","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sauge","quantity":"8","unit":"feuilles","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Huile","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Miel","quantity":"1","unit":"c. à café","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Poivre","quantity":"1","unit":"pincée","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préchauffer le four à 200 °C. Peler les patates douces et les couper en rondelles de 5 mm.","Mélanger les rondelles avec l’huile, le poivre et la moitié de la sauge ciselée. Les étaler sur une plaque et rôtir 15 minutes.","Dérouler la pâte sur une plaque, piquer le centre en laissant une bordure de 3 cm.","Disposer les patates douces sur la pâte, émietter la feta et rabattre la bordure sur la garniture.","Cuire 25 à 30 minutes à 190 °C, jusqu’à ce que la pâte soit dorée et les légumes tendres. Ajouter le miel et le reste de sauge à la sortie du four."]'::jsonb, 'Pour une pâte encore plus croustillante, poser la tarte avec son papier sur une plaque déjà chaude.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['patates douces', 'feta', 'sauge']::text[], array['four', 'plaque de cuisson', 'couteau', 'planche à découper']::text[], 'partial')
ON CONFLICT (id) DO NOTHING;

COMMIT;
