-- City Café batch 08: recettes. Generated from city-cafe-recipes-batch-08.json.
BEGIN;

INSERT INTO public.ingredients (name, category, aliases)
VALUES
  ('Porc', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Oignons', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Ail', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Thym', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Sel et poivre', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Piment', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Carottes', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Bouillon', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Veau', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Basilic', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Agneau', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Épinards', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Pruneaux', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Figues', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Moutarde', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Cheval', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Canard', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Morilles', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Farine', 'Féculents, pains et céréales', '{}'::text[]),
  ('Sucre', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Œufs', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Beurre', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Crème', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Pommes de terre', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Raisins', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Pommes', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Citrons', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Miel', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Cerf', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Cacao', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Faisan', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Curry', 'Épices et herbes aromatiques', '{}'::text[])
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.recipes (id, nom, description, saison, mois, mois_numero, semaine, jour, tag, categorie, theme_special, portions, estimated_time, difficulty, image_url, ingredients, instructions, astuce, cuisson_micro_ondes, sans_four, source, source_pdf, source_page, dietary_tags, main_ingredients, equipment, canonical_ingredients_status)
VALUES
  ('city-cafe-roti-de-porc-et-sauce-charcutiere', 'Rôti de porc et sauce charcutière', 'Rôti de porc et sauce charcutière préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 100, 'facile', 'https://images.pexels.com/photos/8257003/pexels-photo-8257003.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Porc","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates porc dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['porc']::text[], array['porc']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-saute-de-porc-basquaise-au-piment-d-espelette', 'Sauté de porc basquaise au piment d’Espelette', 'Sauté de porc basquaise au piment d’Espelette préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 80, 'facile', 'https://images.pexels.com/photos/32080132/pexels-photo-32080132.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Porc","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Piment","quantity":"300","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['porc']::text[], array['porc', 'piment']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-roti-de-veau-facon-grand-mere-et-pommes-nouvelles-confites', 'Rôti de veau façon grand-mère et pommes nouvelles confites', 'Rôti de veau façon grand-mère et pommes nouvelles confites préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'printemps', 'mai', 5, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 110, 'intermédiaire', 'https://images.pexels.com/photos/7474109/pexels-photo-7474109.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Veau","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates veau dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['veau']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-travers-de-porc-a-la-texane', 'Travers de porc à la texane', 'Travers de porc à la texane préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'juillet', 7, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 150, 'intermédiaire', 'https://images.pexels.com/photos/36242485/pexels-photo-36242485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Porc","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates porc dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['porc']::text[], array['porc']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-emince-de-veau-a-l-italienne-et-basilic', 'Émincé de veau à l’italienne et basilic', 'Émincé de veau à l’italienne et basilic préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 35, 'facile', 'https://images.pexels.com/photos/31064160/pexels-photo-31064160.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Veau","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Basilic","quantity":"150","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates veau, basilic dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['veau', 'basilic']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-boulettes-d-agneau-a-la-libanaise', 'Boulettes d’agneau à la libanaise', 'Boulettes d’agneau à la libanaise préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'printemps', 'mai', 5, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 45, 'facile', 'https://images.pexels.com/photos/16505918/pexels-photo-16505918.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Agneau","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates agneau dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['agneau']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-ribs-de-porc-barbecue-et-pommes-de-terre-roties', 'Ribs de porc barbecue et pommes de terre rôties', 'Ribs de porc barbecue et pommes de terre rôties préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'juin', 6, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 150, 'intermédiaire', 'https://images.pexels.com/photos/16020706/pexels-photo-16020706.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Porc","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates porc dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['porc']::text[], array['porc']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-joue-de-porc-au-cidre-et-lardons-fumes', 'Joue de porc au cidre et lardons fumés', 'Joue de porc au cidre et lardons fumés préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 150, 'intermédiaire', 'https://images.pexels.com/photos/19503818/pexels-photo-19503818.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Porc","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['porc']::text[], array['porc']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-epaule-de-porc-farcie-aux-epinards-et-pruneaux', 'Épaule de porc farcie aux épinards et pruneaux', 'Épaule de porc farcie aux épinards et pruneaux préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'février', 2, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 180, 'intermédiaire', 'https://images.pexels.com/photos/11001291/pexels-photo-11001291.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Épinards","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Porc","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Pruneaux","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates épinards, porc, pruneaux dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['porc']::text[], array['épinards', 'porc', 'pruneaux']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-grenadin-de-porc-sauce-moutarde-et-figues', 'Grenadin de porc, sauce moutarde et figues', 'Grenadin de porc, sauce moutarde et figues préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'septembre', 9, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 40, 'facile', 'https://images.pexels.com/photos/37047950/pexels-photo-37047950.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Porc","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Figues","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Moutarde","quantity":"150","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates porc, figues, moutarde dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['porc']::text[], array['porc', 'figues', 'moutarde']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-pave-de-cheval-et-sauce-bearnaise', 'Pavé de cheval et sauce béarnaise', 'Pavé de cheval et sauce béarnaise préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'juin', 6, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 35, 'facile', 'https://images.pexels.com/photos/39640989/pexels-photo-39640989.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Cheval","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates cheval dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['cheval']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-pave-de-cheval-aux-herbes', 'Pavé de cheval aux herbes', 'Pavé de cheval aux herbes préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'juin', 6, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 25, 'très facile', 'https://images.pexels.com/photos/13322845/pexels-photo-13322845.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Cheval","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates cheval dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['cheval']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-magret-de-canard-roti-et-jus-balsamique', 'Magret de canard rôti et jus balsamique', 'Magret de canard rôti et jus balsamique préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'septembre', 9, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 35, 'facile', 'https://images.pexels.com/photos/19295799/pexels-photo-19295799.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Canard","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates canard dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['canard']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-parmentier-de-canard-mousseline-de-celeri-et-morilles', 'Parmentier de canard, mousseline de céleri et morilles', 'Parmentier de canard, mousseline de céleri et morilles préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'février', 2, null, null, 'dessert', 'sucré', null, '4 personnes', 90, 'facile', 'https://images.pexels.com/photos/29296209/pexels-photo-29296209.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Canard","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Morilles","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Farine","quantity":"300","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Sucre","quantity":"300","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Œufs","quantity":"4","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Beurre","quantity":"120","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"120","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"}]'::jsonb, '["Préchauffer le four à 180 °C. Peser les ingrédients secs et beurrer le moule si cette recette en utilise un.","Mélanger beurre et sucre jusqu’à obtenir une texture crémeuse, puis incorporer les œufs et les ingrédients aromatiques prévus.","Ajouter progressivement les ingrédients secs et les garnitures; mélanger juste assez pour former une préparation homogène.","Cuire selon le format: 10 à 12 min pour des cookies, 25 à 35 min pour un gâteau ou une crème au bain-marie. Laisser refroidir avant de servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, '{}'::text[], array['canard', 'morilles']::text[], array['four', 'saladier', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-filet-de-canard-roti-jus-au-raisin-et-mousseline-de-pomme-de-terre-et-celeri', 'Filet de canard rôti, jus au raisin et mousseline de pomme de terre et céleri', 'Filet de canard rôti, jus au raisin et mousseline de pomme de terre et céleri préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'septembre', 9, null, null, 'dessert', 'sucré', null, '2 personnes', 55, 'facile', 'https://images.pexels.com/photos/14410380/pexels-photo-14410380.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pommes de terre","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Canard","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Raisins","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Pommes","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Farine","quantity":"150","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Sucre","quantity":"150","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Beurre","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"}]'::jsonb, '["Préchauffer le four à 180 °C. Peser les ingrédients secs et beurrer le moule si cette recette en utilise un.","Mélanger beurre et sucre jusqu’à obtenir une texture crémeuse, puis incorporer les œufs et les ingrédients aromatiques prévus.","Ajouter progressivement les ingrédients secs et les garnitures; mélanger juste assez pour former une préparation homogène.","Cuire selon le format: 10 à 12 min pour des cookies, 25 à 35 min pour un gâteau ou une crème au bain-marie. Laisser refroidir avant de servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, '{}'::text[], array['pommes de terre', 'canard', 'raisins', 'pommes']::text[], array['four', 'saladier', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-pastilla-de-canard-aux-fruits-secs-miel-et-citron', 'Pastilla de canard aux fruits secs, miel et citron', 'Pastilla de canard aux fruits secs, miel et citron préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 100, 'facile', 'https://images.pexels.com/photos/36871906/pexels-photo-36871906.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Canard","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Citrons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Miel","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates canard, citrons, miel dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['canard', 'citrons', 'miel']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-civet-de-cerf-au-cacao-et-spatzle', 'Civet de cerf au cacao et spätzle', 'Civet de cerf au cacao et spätzle préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 210, 'intermédiaire', 'https://images.pexels.com/photos/38626233/pexels-photo-38626233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Cerf","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Cacao","quantity":"300","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['cerf', 'cacao']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-saucisse-de-cerf-a-la-moutarde-airelles-et-spatzle', 'Saucisse de cerf à la moutarde, airelles et spätzle', 'Saucisse de cerf à la moutarde, airelles et spätzle préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'novembre', 11, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 35, 'facile', 'https://images.pexels.com/photos/38626236/pexels-photo-38626236.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Cerf","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Moutarde","quantity":"150","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates cerf, moutarde dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['cerf', 'moutarde']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-poitrine-de-faisan-au-raisin-et-sauce-aux-morilles', 'Poitrine de faisan au raisin et sauce aux morilles', 'Poitrine de faisan au raisin et sauce aux morilles préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 50, 'facile', 'https://images.pexels.com/photos/28705621/pexels-photo-28705621.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Faisan","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Raisins","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Morilles","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates faisan, raisins, morilles dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['faisan', 'raisins', 'morilles']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-gigot-d-agneau-au-miel-curry-et-citron', 'Gigot d’agneau au miel, curry et citron', 'Gigot d’agneau au miel, curry et citron préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'printemps', 'avril', 4, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 150, 'intermédiaire', 'https://images.pexels.com/photos/12312117/pexels-photo-12312117.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Agneau","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Citrons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Curry","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Miel","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['agneau', 'citrons', 'curry', 'miel']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified')
ON CONFLICT (id) DO UPDATE SET
  nom = EXCLUDED.nom,
  description = EXCLUDED.description,
  saison = EXCLUDED.saison,
  mois = EXCLUDED.mois,
  mois_numero = EXCLUDED.mois_numero,
  semaine = EXCLUDED.semaine,
  jour = EXCLUDED.jour,
  tag = EXCLUDED.tag,
  categorie = EXCLUDED.categorie,
  theme_special = EXCLUDED.theme_special,
  portions = EXCLUDED.portions,
  estimated_time = EXCLUDED.estimated_time,
  difficulty = EXCLUDED.difficulty,
  image_url = EXCLUDED.image_url,
  ingredients = EXCLUDED.ingredients,
  instructions = EXCLUDED.instructions,
  astuce = EXCLUDED.astuce,
  cuisson_micro_ondes = EXCLUDED.cuisson_micro_ondes,
  sans_four = EXCLUDED.sans_four,
  source = EXCLUDED.source,
  source_pdf = EXCLUDED.source_pdf,
  source_page = EXCLUDED.source_page,
  dietary_tags = EXCLUDED.dietary_tags,
  main_ingredients = EXCLUDED.main_ingredients,
  equipment = EXCLUDED.equipment,
  canonical_ingredients_status = EXCLUDED.canonical_ingredients_status;

-- Keep ingredient JSON category labels aligned with the canonical ingredient catalog.
UPDATE public.recipes AS recipe
SET ingredients = (
  SELECT jsonb_agg(jsonb_set(item.ingredient, '{category}', to_jsonb(canonical.category), true) ORDER BY item.ordinality)
  FROM jsonb_array_elements(recipe.ingredients) WITH ORDINALITY AS item(ingredient, ordinality)
  JOIN public.ingredients AS canonical ON canonical.name = item.ingredient->>'name'
)
WHERE recipe.id IN ('city-cafe-roti-de-porc-et-sauce-charcutiere', 'city-cafe-saute-de-porc-basquaise-au-piment-d-espelette', 'city-cafe-roti-de-veau-facon-grand-mere-et-pommes-nouvelles-confites', 'city-cafe-travers-de-porc-a-la-texane', 'city-cafe-emince-de-veau-a-l-italienne-et-basilic', 'city-cafe-boulettes-d-agneau-a-la-libanaise', 'city-cafe-ribs-de-porc-barbecue-et-pommes-de-terre-roties', 'city-cafe-joue-de-porc-au-cidre-et-lardons-fumes', 'city-cafe-epaule-de-porc-farcie-aux-epinards-et-pruneaux', 'city-cafe-grenadin-de-porc-sauce-moutarde-et-figues', 'city-cafe-pave-de-cheval-et-sauce-bearnaise', 'city-cafe-pave-de-cheval-aux-herbes', 'city-cafe-magret-de-canard-roti-et-jus-balsamique', 'city-cafe-parmentier-de-canard-mousseline-de-celeri-et-morilles', 'city-cafe-filet-de-canard-roti-jus-au-raisin-et-mousseline-de-pomme-de-terre-et-celeri', 'city-cafe-pastilla-de-canard-aux-fruits-secs-miel-et-citron', 'city-cafe-civet-de-cerf-au-cacao-et-spatzle', 'city-cafe-saucisse-de-cerf-a-la-moutarde-airelles-et-spatzle', 'city-cafe-poitrine-de-faisan-au-raisin-et-sauce-aux-morilles', 'city-cafe-gigot-d-agneau-au-miel-curry-et-citron');

-- Keep recipe image choices in sync if reviewed later.
UPDATE public.recipes AS recipe
SET image_url = image.image_url
FROM (VALUES
  ('city-cafe-roti-de-porc-et-sauce-charcutiere', 'https://images.pexels.com/photos/8257003/pexels-photo-8257003.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-saute-de-porc-basquaise-au-piment-d-espelette', 'https://images.pexels.com/photos/32080132/pexels-photo-32080132.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-roti-de-veau-facon-grand-mere-et-pommes-nouvelles-confites', 'https://images.pexels.com/photos/7474109/pexels-photo-7474109.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-travers-de-porc-a-la-texane', 'https://images.pexels.com/photos/36242485/pexels-photo-36242485.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-emince-de-veau-a-l-italienne-et-basilic', 'https://images.pexels.com/photos/31064160/pexels-photo-31064160.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-boulettes-d-agneau-a-la-libanaise', 'https://images.pexels.com/photos/16505918/pexels-photo-16505918.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-ribs-de-porc-barbecue-et-pommes-de-terre-roties', 'https://images.pexels.com/photos/16020706/pexels-photo-16020706.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-joue-de-porc-au-cidre-et-lardons-fumes', 'https://images.pexels.com/photos/19503818/pexels-photo-19503818.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-epaule-de-porc-farcie-aux-epinards-et-pruneaux', 'https://images.pexels.com/photos/11001291/pexels-photo-11001291.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-grenadin-de-porc-sauce-moutarde-et-figues', 'https://images.pexels.com/photos/37047950/pexels-photo-37047950.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-pave-de-cheval-et-sauce-bearnaise', 'https://images.pexels.com/photos/39640989/pexels-photo-39640989.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-pave-de-cheval-aux-herbes', 'https://images.pexels.com/photos/13322845/pexels-photo-13322845.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-magret-de-canard-roti-et-jus-balsamique', 'https://images.pexels.com/photos/19295799/pexels-photo-19295799.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-parmentier-de-canard-mousseline-de-celeri-et-morilles', 'https://images.pexels.com/photos/29296209/pexels-photo-29296209.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-filet-de-canard-roti-jus-au-raisin-et-mousseline-de-pomme-de-terre-et-celeri', 'https://images.pexels.com/photos/14410380/pexels-photo-14410380.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-pastilla-de-canard-aux-fruits-secs-miel-et-citron', 'https://images.pexels.com/photos/36871906/pexels-photo-36871906.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-civet-de-cerf-au-cacao-et-spatzle', 'https://images.pexels.com/photos/38626233/pexels-photo-38626233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-saucisse-de-cerf-a-la-moutarde-airelles-et-spatzle', 'https://images.pexels.com/photos/38626236/pexels-photo-38626236.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-poitrine-de-faisan-au-raisin-et-sauce-aux-morilles', 'https://images.pexels.com/photos/28705621/pexels-photo-28705621.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-gigot-d-agneau-au-miel-curry-et-citron', 'https://images.pexels.com/photos/12312117/pexels-photo-12312117.jpeg?auto=compress&cs=tinysrgb&h=650&w=940')
) AS image(id, image_url)
WHERE recipe.id = image.id;

COMMIT;
