-- City Café batch 10: recettes. Generated from city-cafe-recipes-batch-10.json.
BEGIN;

INSERT INTO public.ingredients (name, category, aliases)
VALUES
  ('Farine', 'Féculents, pains et céréales', '{}'::text[]),
  ('Beurre', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Sucre', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Œufs', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Toblerone', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Levure', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Sel et poivre', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Nutella', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Crème', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Noisettes', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Chocolat', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Noix', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Lait', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Maïzena', 'Féculents, pains et céréales', '{}'::text[]),
  ('Crème glacée', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Flocons d’avoine', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Abricots', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Vanille', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Eau', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Kinder Maxi', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Café', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Pâte feuilletée', 'Féculents, pains et céréales', '{}'::text[]),
  ('Amandes', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Chocolat blanc', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Cranberries séchées', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Riz', 'Féculents, pains et céréales', '{}'::text[]),
  ('Citron vert', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Gélatine', 'Fruits, légumes et légumineuses', '{}'::text[])
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.recipes (id, nom, description, saison, mois, mois_numero, semaine, jour, tag, categorie, theme_special, portions, estimated_time, difficulty, image_url, ingredients, instructions, astuce, cuisson_micro_ondes, sans_four, source, source_pdf, source_page, dietary_tags, main_ingredients, equipment, canonical_ingredients_status)
VALUES
  ('city-cafe-cookies-au-toblerone', 'Cookies au Toblerone', 'Cookies moelleux au beurre, garnis de morceaux de Toblerone fondants et de nougat aux amandes.', 'hiver', 'décembre', 12, null, null, 'dessert', 'sucré', null, '4 personnes', 30, 'très facile', 'https://images.pexels.com/photos/9919649/pexels-photo-9919649.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Farine","quantity":"180","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Beurre","quantity":"100","unit":"g mou","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sucre","quantity":"70","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Œufs","quantity":"1","unit":"pièce","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Toblerone","quantity":"120","unit":"g concassé","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Levure","quantity":"1","unit":"c. à café","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Sel et poivre","quantity":"1","unit":"pincée","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préchauffer le four à 180 °C et couvrir une plaque de papier cuisson.","Fouetter le beurre mou et le sucre 2 minutes. Incorporer l’œuf.","Mélanger la farine, la levure et une pincée de sel; les incorporer sans trop travailler la pâte.","Ajouter le Toblerone concassé, former 8 boules et les espacer sur la plaque.","Cuire 10 à 12 minutes: les bords doivent être pris et le centre encore tendre. Laisser reposer 10 minutes sur la plaque."]'::jsonb, 'Réserver quelques morceaux de Toblerone pour les déposer sur les cookies juste avant la cuisson.', false, true, 'broco-chou', null, null, '{}'::text[], array['farine', 'beurre', 'sucre', 'œufs']::text[], array['four', 'plaque de cuisson', 'saladier', 'fouet']::text[], 'verified'),
  ('city-cafe-mousse-au-nutella-et-noisettes-caramelisees', 'Mousse au Nutella et noisettes caramélisées', 'Mousse aérienne au Nutella servie avec des noisettes enrobées d’un caramel blond.', 'hiver', 'février', 2, null, null, 'dessert', 'sucré', null, '4 personnes', 35, 'facile', 'https://images.pexels.com/photos/14738384/pexels-photo-14738384.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Nutella","quantity":"180","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Crème","quantity":"25","unit":"cl très froide","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Noisettes","quantity":"50","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Sucre","quantity":"35","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Sel et poivre","quantity":"1","unit":"pincée","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Placer un saladier et les fouets au froid 10 minutes. Faire chauffer le Nutella quelques secondes pour l’assouplir, puis le laisser tiédir.","Fouetter la crème froide en chantilly souple. Incorporer d’abord une cuillerée de crème au Nutella, puis le reste délicatement à la spatule.","Répartir dans quatre verrines et réserver au réfrigérateur au moins 2 heures.","Torréfier les noisettes 5 minutes à sec. Faire fondre le sucre dans une petite casserole jusqu’à obtenir un caramel blond, ajouter les noisettes et mélanger.","Étaler sur du papier cuisson, laisser refroidir puis concasser. Parsemer sur les mousses au moment de servir."]'::jsonb, 'La mousse se prépare la veille; ajouter les noisettes caramélisées au dernier moment pour qu’elles restent croquantes.', false, true, 'broco-chou', null, null, '{}'::text[], array['nutella', 'crème', 'noisettes', 'sucre']::text[], array['casserole', 'saladier', 'fouet', 'ramequins', 'four']::text[], 'verified'),
  ('city-cafe-cookies-au-chocolat-et-noix-de-grenoble', 'Cookies au chocolat et noix de Grenoble', 'Cookies au chocolat noir et aux éclats de noix de Grenoble, croustillants sur les bords et moelleux au centre.', 'automne', 'octobre', 10, null, null, 'dessert', 'sucré', null, '4 personnes', 30, 'très facile', 'https://images.pexels.com/photos/5640103/pexels-photo-5640103.png?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Farine","quantity":"180","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Beurre","quantity":"100","unit":"g mou","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sucre","quantity":"90","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Œufs","quantity":"1","unit":"pièce","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Chocolat","quantity":"100","unit":"g noir concassé","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Noix","quantity":"60","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Levure","quantity":"1","unit":"c. à café","canonical":true,"category":"Fruits, légumes et légumineuses"}]'::jsonb, '["Préchauffer le four à 180 °C et tapisser une plaque de papier cuisson.","Crémer le beurre avec le sucre, incorporer l’œuf puis la farine et la levure.","Ajouter le chocolat concassé et les noix grossièrement hachées.","Former 8 boules, les déposer en les espaçant et les aplatir légèrement.","Cuire 10 à 12 minutes. Laisser refroidir 10 minutes sur la plaque avant de déplacer."]'::jsonb, 'Sortir les cookies quand leur centre paraît encore tendre: ils finiront de prendre en refroidissant.', false, true, 'broco-chou', null, null, '{}'::text[], array['farine', 'beurre', 'sucre', 'œufs']::text[], array['four', 'plaque de cuisson', 'saladier', 'fouet']::text[], 'verified'),
  ('city-cafe-chocolat-liegeois', 'Chocolat liégeois', 'Crème chocolatée onctueuse refroidie, surmontée de glace vanille et de crème fouettée.', 'hiver', 'février', 2, null, null, 'dessert', 'sucré', null, '2 personnes', 25, 'très facile', 'https://images.pexels.com/photos/30146049/pexels-photo-30146049.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Lait","quantity":"40","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Chocolat","quantity":"80","unit":"g noir","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Sucre","quantity":"25","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Maïzena","quantity":"12","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Crème glacée","quantity":"2","unit":"boules vanille","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"10","unit":"cl entière froide","canonical":true,"category":"Crèmerie et produits laitiers"}]'::jsonb, '["Délayer la Maïzena et le sucre dans un peu de lait froid. Chauffer le reste du lait.","Ajouter le chocolat haché au lait chaud et remuer jusqu’à fonte. Verser le mélange de Maïzena en fouettant.","Cuire à feu moyen 2 à 3 minutes jusqu’à épaississement. Répartir dans deux verres et réfrigérer au moins 2 heures.","Fouetter la crème froide en chantilly. Déposer une boule de glace vanille sur chaque crème chocolatée puis ajouter la chantilly.","Servir immédiatement, éventuellement avec des copeaux de chocolat."]'::jsonb, 'Refroidir les crèmes avant d’ajouter la glace pour éviter qu’elle ne fonde au dressage.', false, true, 'broco-chou', null, null, '{}'::text[], array['lait', 'chocolat', 'sucre', 'maïzena']::text[], array['casserole', 'saladier', 'fouet', 'ramequins', 'four']::text[], 'verified'),
  ('city-cafe-cookies-aux-abricots-et-flocons-d-avoine', 'Cookies aux abricots et flocons d’avoine', 'Cookies rustiques aux flocons d’avoine et aux morceaux d’abricot moelleux.', 'été', 'juillet', 7, null, null, 'dessert', 'sucré', null, '4 personnes', 30, 'très facile', 'https://images.pexels.com/photos/6608722/pexels-photo-6608722.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Flocons d’avoine","quantity":"120","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Farine","quantity":"100","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Beurre","quantity":"90","unit":"g mou","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sucre","quantity":"70","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Œufs","quantity":"1","unit":"pièce","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Abricots","quantity":"100","unit":"g secs en dés","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Levure","quantity":"1","unit":"c. à café","canonical":true,"category":"Fruits, légumes et légumineuses"}]'::jsonb, '["Préchauffer le four à 180 °C et tapisser une plaque de papier cuisson.","Mélanger le beurre mou et le sucre, puis incorporer l’œuf.","Ajouter farine, flocons d’avoine et levure; mélanger juste assez pour obtenir une pâte épaisse.","Couper les abricots secs en dés et les incorporer. Former 8 cookies et les déposer sur la plaque.","Cuire 12 à 14 minutes jusqu’à légère coloration des bords. Laisser refroidir sur la plaque."]'::jsonb, 'Si les abricots secs sont fermes, les réhydrater 10 minutes dans de l’eau tiède puis bien les sécher.', false, true, 'broco-chou', null, null, '{}'::text[], array['flocons d’avoine', 'farine', 'beurre', 'sucre']::text[], array['four', 'plaque de cuisson', 'saladier', 'fouet']::text[], 'verified'),
  ('city-cafe-creme-caramel', 'Crème caramel', 'Crème prise aux œufs nappée d’un caramel ambré, cuite doucement au bain-marie.', 'hiver', 'janvier', 1, null, null, 'dessert', 'sucré', null, '4 personnes', 65, 'facile', 'https://images.pexels.com/photos/36295521/pexels-photo-36295521.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Œufs","quantity":"3","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Lait","quantity":"50","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sucre","quantity":"110","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Vanille","quantity":"1","unit":"gousse","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Eau","quantity":"2","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préchauffer le four à 160 °C. Faire fondre 60 g de sucre avec l’eau dans une casserole sans remuer jusqu’à obtenir un caramel ambré.","Répartir le caramel dans quatre ramequins et laisser durcir.","Chauffer le lait avec la vanille. Fouetter les œufs avec les 50 g de sucre restants sans faire mousser, puis verser le lait chaud en filet.","Filtrer l’appareil dans les ramequins. Les poser dans un plat et verser de l’eau chaude à mi-hauteur.","Cuire au bain-marie 35 à 40 minutes, jusqu’à ce que les crèmes soient prises mais encore légèrement tremblotantes. Refroidir puis réfrigérer 4 heures avant de démouler."]'::jsonb, 'Passer la lame d’un couteau autour des ramequins et les tremper quelques secondes dans l’eau chaude pour faciliter le démoulage.', false, true, 'broco-chou', null, null, '{}'::text[], array['œufs', 'lait', 'sucre', 'vanille']::text[], array['casserole', 'saladier', 'fouet', 'ramequins', 'four']::text[], 'verified'),
  ('city-cafe-cookies-au-kinder-maxi', 'Cookies au Kinder Maxi', 'Cookies moelleux ponctués de morceaux fondants de Kinder Maxi au lait et au chocolat.', 'hiver', 'décembre', 12, null, null, 'dessert', 'sucré', null, '4 personnes', 30, 'très facile', 'https://images.pexels.com/photos/37353913/pexels-photo-37353913.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Farine","quantity":"180","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Beurre","quantity":"100","unit":"g mou","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sucre","quantity":"70","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Œufs","quantity":"1","unit":"pièce","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Kinder Maxi","quantity":"120","unit":"g en morceaux","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Levure","quantity":"1","unit":"c. à café","canonical":true,"category":"Fruits, légumes et légumineuses"}]'::jsonb, '["Préchauffer le four à 180 °C et couvrir une plaque de papier cuisson.","Fouetter le beurre mou avec le sucre, puis incorporer l’œuf.","Ajouter la farine et la levure. Mélanger brièvement puis incorporer les morceaux de Kinder Maxi.","Former 8 boules espacées sur la plaque et les aplatir légèrement.","Cuire 10 à 12 minutes jusqu’à ce que les bords soient dorés. Laisser reposer avant de servir."]'::jsonb, 'Réserver les morceaux de chocolat au frais jusqu’au montage pour qu’ils gardent leur forme à la cuisson.', false, true, 'broco-chou', null, null, '{}'::text[], array['farine', 'beurre', 'sucre', 'œufs']::text[], array['four', 'plaque de cuisson', 'saladier', 'fouet']::text[], 'verified'),
  ('city-cafe-clafoutis-aux-abricots', 'Clafoutis aux abricots', 'Clafoutis tendre aux abricots frais, dans un appareil léger à base d’œufs et de lait.', 'été', 'juillet', 7, null, null, 'dessert', 'sucré', null, '4 personnes', 55, 'facile', 'https://images.pexels.com/photos/38588704/pexels-photo-38588704.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Abricots","quantity":"450","unit":"g dénoyautés","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"3","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Farine","quantity":"90","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Sucre","quantity":"70","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Lait","quantity":"25","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Beurre","quantity":"20","unit":"g pour le moule","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Vanille","quantity":"1","unit":"c. à café","canonical":true,"category":"Fruits, légumes et légumineuses"}]'::jsonb, '["Préchauffer le four à 180 °C et beurrer un plat de 24 cm.","Laver, sécher, dénoyauter les abricots et les couper en quartiers. Les répartir dans le plat.","Fouetter les œufs et le sucre. Ajouter la farine, puis le lait et la vanille en fouettant pour éviter les grumeaux.","Verser l’appareil sur les abricots et enfourner 35 à 40 minutes, jusqu’à ce que le centre soit pris et le dessus doré.","Laisser tiédir 15 minutes avant de servir."]'::jsonb, 'Choisir des abricots mûrs mais encore fermes afin qu’ils gardent leur tenue à la cuisson.', false, true, 'broco-chou', null, null, '{}'::text[], array['abricots', 'œufs', 'farine', 'sucre']::text[], array['casserole', 'saladier', 'fouet', 'ramequins', 'four']::text[], 'verified'),
  ('city-cafe-cookies-au-cafe-et-chocolat', 'Cookies au café et chocolat', 'Cookies au café espresso et au chocolat noir, avec une pâte riche et légèrement amère.', 'automne', 'octobre', 10, null, null, 'dessert', 'sucré', null, '4 personnes', 30, 'très facile', 'https://images.pexels.com/photos/32024868/pexels-photo-32024868.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Farine","quantity":"180","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Beurre","quantity":"100","unit":"g mou","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sucre","quantity":"85","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Œufs","quantity":"1","unit":"pièce","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Chocolat","quantity":"100","unit":"g noir","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Café","quantity":"2","unit":"c. à café espresso refroidi","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Levure","quantity":"1","unit":"c. à café","canonical":true,"category":"Fruits, légumes et légumineuses"}]'::jsonb, '["Préchauffer le four à 180 °C et tapisser une plaque de papier cuisson.","Crémer le beurre et le sucre. Incorporer l’œuf et le café refroidi.","Ajouter la farine et la levure, puis le chocolat concassé.","Former 8 boules, les espacer sur la plaque et les aplatir légèrement.","Cuire 10 à 12 minutes. Laisser refroidir sur la plaque pour que le centre se raffermisse."]'::jsonb, 'Un espresso serré refroidi apporte plus de goût sans détendre la pâte comme le ferait un grand café.', false, true, 'broco-chou', null, null, '{}'::text[], array['farine', 'beurre', 'sucre', 'œufs']::text[], array['four', 'plaque de cuisson', 'saladier', 'fouet']::text[], 'verified'),
  ('city-cafe-galette-des-rois', 'Galette des rois', 'Galette dorée garnie d’une frangipane aux amandes, assemblée avec une pâte feuilletée du commerce.', 'hiver', 'janvier', 1, null, null, 'dessert', 'sucré', null, '4 personnes', 60, 'facile', 'https://images.pexels.com/photos/6072098/pexels-photo-6072098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte feuilletée","quantity":"2","unit":"rouleaux ronds","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Amandes","quantity":"125","unit":"g poudre","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Beurre","quantity":"100","unit":"g mou","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sucre","quantity":"100","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Vanille","quantity":"1","unit":"c. à café","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Lait","quantity":"1","unit":"c. à soupe pour la dorure","canonical":true,"category":"Crèmerie et produits laitiers"}]'::jsonb, '["Préchauffer le four à 190 °C. Fouetter le beurre et le sucre, puis incorporer la poudre d’amandes, un œuf et la vanille.","Dérouler un disque de pâte sur une plaque. Étaler la frangipane au centre en laissant une bordure de 2 cm; placer une fève si souhaité.","Humidifier la bordure, couvrir du second disque et souder soigneusement. Dessiner des motifs sans percer la pâte.","Dorer avec le second œuf battu avec le lait, puis réfrigérer 15 minutes pour raffermir la pâte.","Dorer une seconde fois et cuire 30 à 35 minutes jusqu’à ce que la galette soit bien gonflée et dorée. Laisser tiédir avant de couper."]'::jsonb, 'Une pâte feuilletée pur beurre du commerce donne un résultat régulier sans exiger le tourage à la maison.', false, true, 'broco-chou', null, null, '{}'::text[], array['pâte feuilletée', 'amandes', 'beurre', 'sucre']::text[], array['casserole', 'saladier', 'fouet', 'ramequins', 'four']::text[], 'verified'),
  ('city-cafe-cookies-aux-cranberries-et-chocolat-blanc', 'Cookies aux cranberries et chocolat blanc', 'Cookies doux au chocolat blanc, équilibrés par l’acidité des cranberries séchées.', 'hiver', 'décembre', 12, null, null, 'dessert', 'sucré', null, '4 personnes', 30, 'très facile', 'https://images.pexels.com/photos/15794484/pexels-photo-15794484.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Farine","quantity":"180","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Beurre","quantity":"100","unit":"g mou","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sucre","quantity":"75","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Œufs","quantity":"1","unit":"pièce","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Chocolat blanc","quantity":"100","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Cranberries séchées","quantity":"70","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Levure","quantity":"1","unit":"c. à café","canonical":true,"category":"Fruits, légumes et légumineuses"}]'::jsonb, '["Préchauffer le four à 180 °C et tapisser une plaque de papier cuisson.","Crémer le beurre et le sucre, puis incorporer l’œuf.","Mélanger la farine et la levure, les ajouter à la pâte, puis incorporer le chocolat blanc en morceaux et les cranberries.","Former 8 boules espacées sur la plaque et les aplatir légèrement.","Cuire 10 à 12 minutes jusqu’à légère coloration des bords. Laisser refroidir sur la plaque."]'::jsonb, 'Si les cranberries sont très sèches, les faire tremper 5 minutes puis les sécher soigneusement.', false, true, 'broco-chou', null, null, '{}'::text[], array['farine', 'beurre', 'sucre', 'œufs']::text[], array['four', 'plaque de cuisson', 'saladier', 'fouet']::text[], 'verified'),
  ('city-cafe-riz-au-lait-et-gel-de-citron-vert', 'Riz au lait et gel de citron vert', 'Riz au lait crémeux refroidi, accompagné d’un gel acidulé au citron vert.', 'printemps', 'avril', 4, null, null, 'dessert', 'sucré', null, '4 personnes', 55, 'facile', 'https://images.pexels.com/photos/36452148/pexels-photo-36452148.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Riz","quantity":"120","unit":"g rond","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Lait","quantity":"75","unit":"cl","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sucre","quantity":"90","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Vanille","quantity":"1","unit":"gousse","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Citron vert","quantity":"2","unit":"zestes et jus","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Gélatine","quantity":"2","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"}]'::jsonb, '["Rincer rapidement le riz. Le verser dans une casserole avec le lait et la vanille; cuire à feu très doux 35 à 40 minutes en remuant souvent.","Ajouter 65 g de sucre dans les 10 dernières minutes. Répartir le riz au lait dans quatre verrines et laisser refroidir.","Faire tremper la gélatine dans l’eau froide. Chauffer le jus et le zeste de citron vert avec 25 g de sucre et 2 c. à soupe d’eau.","Hors du feu, incorporer la gélatine essorée, mélanger puis laisser refroidir jusqu’à ce que le gel commence à épaissir.","Répartir le gel sur le riz au lait froid et réfrigérer au moins 1 heure avant de servir."]'::jsonb, 'Ne laissez pas le riz au lait sans surveillance: remuez fréquemment et ajoutez un peu de lait s’il épaissit trop.', false, true, 'broco-chou', null, null, '{}'::text[], array['riz', 'lait', 'sucre', 'vanille']::text[], array['casserole', 'saladier', 'fouet', 'ramequins', 'four']::text[], 'verified')
ON CONFLICT (id) DO UPDATE SET
  nom = EXCLUDED.nom,
  description = EXCLUDED.description,
  saison = EXCLUDED.saison,
  mois = EXCLUDED.mois,
  mois_numero = EXCLUDED.mois_numero,
  semaine = EXCLUDED.semaine,
  jour = EXCLUDED.jour,
  tag = EXCLUDED.tag,
  categorie = EXCLUDED.categorie,
  theme_special = EXCLUDED.theme_special,
  portions = EXCLUDED.portions,
  estimated_time = EXCLUDED.estimated_time,
  difficulty = EXCLUDED.difficulty,
  image_url = EXCLUDED.image_url,
  ingredients = EXCLUDED.ingredients,
  instructions = EXCLUDED.instructions,
  astuce = EXCLUDED.astuce,
  cuisson_micro_ondes = EXCLUDED.cuisson_micro_ondes,
  sans_four = EXCLUDED.sans_four,
  source = EXCLUDED.source,
  source_pdf = EXCLUDED.source_pdf,
  source_page = EXCLUDED.source_page,
  dietary_tags = EXCLUDED.dietary_tags,
  main_ingredients = EXCLUDED.main_ingredients,
  equipment = EXCLUDED.equipment,
  canonical_ingredients_status = EXCLUDED.canonical_ingredients_status;

-- Keep ingredient JSON category labels aligned with the canonical ingredient catalog.
UPDATE public.recipes AS recipe
SET ingredients = (
  SELECT jsonb_agg(jsonb_set(item.ingredient, '{category}', to_jsonb(canonical.category), true) ORDER BY item.ordinality)
  FROM jsonb_array_elements(recipe.ingredients) WITH ORDINALITY AS item(ingredient, ordinality)
  JOIN public.ingredients AS canonical ON canonical.name = item.ingredient->>'name'
)
WHERE recipe.id IN ('city-cafe-cookies-au-toblerone', 'city-cafe-mousse-au-nutella-et-noisettes-caramelisees', 'city-cafe-cookies-au-chocolat-et-noix-de-grenoble', 'city-cafe-chocolat-liegeois', 'city-cafe-cookies-aux-abricots-et-flocons-d-avoine', 'city-cafe-creme-caramel', 'city-cafe-cookies-au-kinder-maxi', 'city-cafe-clafoutis-aux-abricots', 'city-cafe-cookies-au-cafe-et-chocolat', 'city-cafe-galette-des-rois', 'city-cafe-cookies-aux-cranberries-et-chocolat-blanc', 'city-cafe-riz-au-lait-et-gel-de-citron-vert');

-- Keep recipe image choices in sync if reviewed later.
UPDATE public.recipes AS recipe
SET image_url = image.image_url
FROM (VALUES
  ('city-cafe-cookies-au-toblerone', 'https://images.pexels.com/photos/9919649/pexels-photo-9919649.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-mousse-au-nutella-et-noisettes-caramelisees', 'https://images.pexels.com/photos/14738384/pexels-photo-14738384.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-cookies-au-chocolat-et-noix-de-grenoble', 'https://images.pexels.com/photos/5640103/pexels-photo-5640103.png?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-chocolat-liegeois', 'https://images.pexels.com/photos/30146049/pexels-photo-30146049.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-cookies-aux-abricots-et-flocons-d-avoine', 'https://images.pexels.com/photos/6608722/pexels-photo-6608722.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-creme-caramel', 'https://images.pexels.com/photos/36295521/pexels-photo-36295521.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-cookies-au-kinder-maxi', 'https://images.pexels.com/photos/37353913/pexels-photo-37353913.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-clafoutis-aux-abricots', 'https://images.pexels.com/photos/38588704/pexels-photo-38588704.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-cookies-au-cafe-et-chocolat', 'https://images.pexels.com/photos/32024868/pexels-photo-32024868.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-galette-des-rois', 'https://images.pexels.com/photos/6072098/pexels-photo-6072098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-cookies-aux-cranberries-et-chocolat-blanc', 'https://images.pexels.com/photos/15794484/pexels-photo-15794484.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-riz-au-lait-et-gel-de-citron-vert', 'https://images.pexels.com/photos/36452148/pexels-photo-36452148.jpeg?auto=compress&cs=tinysrgb&h=650&w=940')
) AS image(id, image_url)
WHERE recipe.id = image.id;

COMMIT;
