-- City Café batch 04: recettes. Generated from city-cafe-recipes-batch-04.json.
BEGIN;

INSERT INTO public.ingredients (name, category, aliases)
VALUES
  ('Pommes de terre', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Tomates', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Mozzarella di bufala', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Œufs', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Farine', 'Féculents, pains et céréales', '{}'::text[]),
  ('Huile d''olive', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Basilic', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Pâte à pizza', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Courgettes', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Poivrons', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Oignons', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Mozzarella', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Origan', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Champignons de Paris', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Gorgonzola', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Parmesan', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Crème', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Roquette', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Potimarron', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Oignons rouges', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Ricotta', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Thym', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Persil', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Tomates cerises', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Chèvre', 'Crèmerie et produits laitiers', '{}'::text[])
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.recipes (id, nom, description, saison, mois, mois_numero, semaine, jour, tag, categorie, theme_special, portions, estimated_time, difficulty, image_url, ingredients, instructions, astuce, cuisson_micro_ondes, sans_four, source, source_pdf, source_page, dietary_tags, main_ingredients, equipment, canonical_ingredients_status)
VALUES
  ('city-cafe-rosti-pizza-tomate-mozzarella-bufala', 'Rösti-pizza à la tomate et mozzarella di bufala', 'Une base croustillante de pommes de terre râpées remplace la pâte, garnie de tomate et de mozzarella di bufala fondante.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 50, 'intermédiaire', 'https://images.pexels.com/photos/30232158/pexels-photo-30232158.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pommes de terre","quantity":"500","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Tomates","quantity":"200","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Mozzarella di bufala","quantity":"125","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Œufs","quantity":"1","unit":"pièce","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Farine","quantity":"20","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Huile d''olive","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Basilic","quantity":"8","unit":"feuilles","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préchauffer le four à 220 °C. Râper les pommes de terre, les presser dans un torchon propre pour retirer leur eau puis les mélanger avec l’œuf, la farine, du sel et du poivre.","Étaler en disque de 1 cm sur une plaque huilée et enfourner 20 minutes; retourner délicatement et cuire encore 10 minutes.","Couper les tomates en rondelles et égoutter la mozzarella. Répartir sur la base dorée.","Enfourner 8 à 10 minutes, jusqu’à ce que le fromage soit juste fondu. Ajouter le basilic et servir chaud."]'::jsonb, 'Pressez soigneusement les pommes de terre râpées: une base sèche devient plus croustillante.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['pommes de terre', 'tomates', 'mozzarella di bufala']::text[], array['four', 'plaque de cuisson', 'râpe', 'torchon propre', 'saladier']::text[], 'verified'),
  ('city-cafe-pizza-maison-legumes-rotis', 'Pizza maison aux légumes rôtis', 'Une pizza familiale garnie de courgette, poivron et oignon rôtis, avec tomate et mozzarella.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 55, 'facile', 'https://images.pexels.com/photos/30818094/pexels-photo-30818094.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte à pizza","quantity":"1","unit":"boule de 400 g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Courgettes","quantity":"200","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Poivrons","quantity":"1","unit":"pièce","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Oignons","quantity":"1","unit":"pièce","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Tomates","quantity":"200","unit":"g concassées","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Mozzarella","quantity":"150","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Huile d''olive","quantity":"2","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Origan","quantity":"1","unit":"c. à café","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Chauffer le four à 220 °C. Couper la courgette, le poivron et l’oignon en morceaux, mélanger avec une cuillère d’huile et rôtir 18 minutes sur une plaque.","Étaler la pâte sur une plaque farinée. Étaler les tomates concassées en laissant un bord libre.","Répartir la mozzarella égouttée puis les légumes rôtis. Ajouter l’origan et le reste d’huile.","Cuire 12 à 15 minutes, jusqu’à ce que la pâte soit gonflée et dorée. Laisser reposer 2 minutes avant de trancher."]'::jsonb, 'Rôtir les légumes avant le montage évite qu’ils ne détrempent la pâte.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['pâte à pizza', 'courgettes', 'poivrons', 'mozzarella']::text[], array['four', 'plaque de cuisson', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-pizza-trois-fromages-champignons-roquette', 'Pizza aux trois fromages, champignons et roquette', 'Une pizza généreuse au fromage fondant et aux champignons dorés, réveillée par la roquette ajoutée après cuisson.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 40, 'facile', 'https://images.pexels.com/photos/17478671/pexels-photo-17478671.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte à pizza","quantity":"1","unit":"boule de 250 g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Champignons de Paris","quantity":"150","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Mozzarella","quantity":"80","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Gorgonzola","quantity":"50","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Parmesan","quantity":"25","unit":"g râpé","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"2","unit":"c. à soupe","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Roquette","quantity":"30","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Huile d''olive","quantity":"1","unit":"c. à café","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préchauffer le four à 230 °C avec une plaque à l’intérieur. Émincer les champignons et les faire revenir 5 minutes à la poêle avec l’huile.","Étaler la pâte sur du papier cuisson. Étaler la crème en couche fine, puis répartir mozzarella, gorgonzola, parmesan et champignons.","Faire glisser la pizza sur la plaque chaude et cuire 10 à 13 minutes, jusqu’à ce que les bords soient bien dorés.","Garnir de roquette juste avant de servir."]'::jsonb, 'La roquette ajoutée à la sortie du four garde son croquant et son goût poivré.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['mozzarella', 'gorgonzola', 'champignons', 'roquette']::text[], array['four', 'plaque de cuisson', 'poêle', 'couteau']::text[], 'verified'),
  ('city-cafe-pizza-legumes-automne-ricotta-herbes', 'Pizza aux légumes d’automne rôtis et ricotta aux herbes', 'Courge et oignon rôtis sur une pâte croustillante, ponctués de ricotta fraîche parfumée aux herbes.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 55, 'facile', 'https://images.pexels.com/photos/7362681/pexels-photo-7362681.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte à pizza","quantity":"1","unit":"boule de 250 g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Potimarron","quantity":"250","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Oignons rouges","quantity":"1","unit":"pièce","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Ricotta","quantity":"100","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Thym","quantity":"1","unit":"c. à café","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Huile d''olive","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Persil","quantity":"1","unit":"c. à soupe hachée","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préchauffer le four à 210 °C. Épépiner le potimarron et le couper en fines tranches; émincer l’oignon.","Mélanger les légumes avec l’huile, le thym, du sel et du poivre puis rôtir 20 minutes, jusqu’à tendreté.","Augmenter le four à 230 °C. Étaler la pâte sur une plaque et répartir les légumes rôtis.","Cuire 12 à 15 minutes. Détendre la ricotta avec le persil et une cuillère d’eau, puis déposer en petites cuillerées sur la pizza chaude."]'::jsonb, 'Le potimarron peut être utilisé avec sa peau après lavage: elle s’attendrit à la cuisson.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['potimarron', 'ricotta', 'pâte à pizza']::text[], array['four', 'plaque de cuisson', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-margherita-quatre-fromages-tomates-cerises', 'Pizza Margherita aux quatre fromages et coulis de tomates cerises', 'Une base de tomates cerises fraîches mixées, garnie de mozzarella, chèvre, gorgonzola et parmesan.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 40, 'facile', 'https://images.pexels.com/photos/33457997/pexels-photo-33457997.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte à pizza","quantity":"1","unit":"boule de 250 g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Tomates cerises","quantity":"250","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Mozzarella","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Chèvre","quantity":"40","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Gorgonzola","quantity":"35","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Parmesan","quantity":"20","unit":"g râpé","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Basilic","quantity":"8","unit":"feuilles","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Huile d''olive","quantity":"1","unit":"c. à café","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préchauffer le four à 230 °C avec une plaque. Mixer les tomates cerises avec l’huile et une pincée de sel; faire réduire 8 minutes dans une petite casserole.","Étaler la pâte et répartir le coulis refroidi en fine couche. Égoutter la mozzarella et la couper en morceaux.","Ajouter mozzarella, chèvre émietté, gorgonzola et parmesan.","Cuire 10 à 13 minutes sur la plaque chaude. Parsemer de basilic à la sortie du four et servir."]'::jsonb, 'Goûtez le coulis avant de l’étaler et faites-le réduire davantage s’il est très aqueux.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['tomates cerises', 'mozzarella', 'chèvre', 'gorgonzola', 'parmesan']::text[], array['four', 'plaque de cuisson', 'mixeur', 'casserole']::text[], 'verified')
ON CONFLICT (id) DO NOTHING;

-- Keep ingredient JSON category labels aligned with the canonical ingredient catalog.
UPDATE public.recipes AS recipe
SET ingredients = (
  SELECT jsonb_agg(jsonb_set(item.ingredient, '{category}', to_jsonb(canonical.category), true) ORDER BY item.ordinality)
  FROM jsonb_array_elements(recipe.ingredients) WITH ORDINALITY AS item(ingredient, ordinality)
  JOIN public.ingredients AS canonical ON canonical.name = item.ingredient->>'name'
)
WHERE recipe.id IN ('city-cafe-rosti-pizza-tomate-mozzarella-bufala', 'city-cafe-pizza-maison-legumes-rotis', 'city-cafe-pizza-trois-fromages-champignons-roquette', 'city-cafe-pizza-legumes-automne-ricotta-herbes', 'city-cafe-margherita-quatre-fromages-tomates-cerises');

-- Keep recipe image choices in sync if reviewed later.
UPDATE public.recipes AS recipe
SET image_url = image.image_url
FROM (VALUES
  ('city-cafe-rosti-pizza-tomate-mozzarella-bufala', 'https://images.pexels.com/photos/30232158/pexels-photo-30232158.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-pizza-maison-legumes-rotis', 'https://images.pexels.com/photos/30818094/pexels-photo-30818094.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-pizza-trois-fromages-champignons-roquette', 'https://images.pexels.com/photos/17478671/pexels-photo-17478671.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-pizza-legumes-automne-ricotta-herbes', 'https://images.pexels.com/photos/7362681/pexels-photo-7362681.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-margherita-quatre-fromages-tomates-cerises', 'https://images.pexels.com/photos/33457997/pexels-photo-33457997.jpeg?auto=compress&cs=tinysrgb&h=650&w=940')
) AS image(id, image_url)
WHERE recipe.id = image.id;

COMMIT;
