-- City Café batch 06: recettes. Generated from city-cafe-recipes-batch-06.json.
BEGIN;

INSERT INTO public.ingredients (name, category, aliases)
VALUES
  ('Poulet', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Morilles', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Oignons', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Ail', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Thym', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Sel et poivre', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Crème', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Pommes de terre', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Œufs', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Fromage frais', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Cheddar', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Poisson blanc', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Huile d''olive', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Citrons', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Persil', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Beurre', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Avocats', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Pain', 'Féculents, pains et céréales', '{}'::text[]),
  ('Salade', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Tomates', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Pain naan', 'Féculents, pains et céréales', '{}'::text[]),
  ('Dinde / volaille', 'Fruits, légumes et légumineuses', '{}'::text[])
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.recipes (id, nom, description, saison, mois, mois_numero, semaine, jour, tag, categorie, theme_special, portions, estimated_time, difficulty, image_url, ingredients, instructions, astuce, cuisson_micro_ondes, sans_four, source, source_pdf, source_page, dietary_tags, main_ingredients, equipment, canonical_ingredients_status)
VALUES
  ('city-cafe-supreme-de-poulet-roti-sauce-aux-morilles', 'Suprême de poulet rôti, sauce aux morilles', 'Suprême de poulet rôti, sauce aux morilles préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'printemps', 'avril', 4, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 55, 'facile', 'https://images.pexels.com/photos/36863872/pexels-photo-36863872.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Poulet","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Morilles","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates poulet, morilles dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['volaille']::text[], array['poulet', 'morilles']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-tenders-de-poulet-et-sauce-cajun', 'Tenders de poulet et sauce cajun', 'Tenders de poulet et sauce cajun préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'juin', 6, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 35, 'facile', 'https://images.pexels.com/photos/8859016/pexels-photo-8859016.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Poulet","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates poulet dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['volaille']::text[], array['poulet']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-supreme-de-poulet-roti-jus-creme-et-gratin-dauphinois', 'Suprême de poulet rôti, jus crémé et gratin dauphinois', 'Suprême de poulet rôti, jus crémé et gratin dauphinois préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 90, 'facile', 'https://images.pexels.com/photos/20150680/pexels-photo-20150680.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Crème","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Poulet","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Pommes de terre","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Fromage frais","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préchauffer le four à 190 °C. Préparer la garniture crème, poulet et cuire au préalable les légumes humides dans une poêle pour évacuer leur eau.","Foncer le moule ou la plaque avec la pâte; piquer le fond. Mélanger les œufs, la crème et le fromage, puis assaisonner.","Répartir la garniture, verser l’appareil ou la sauce et enfourner 30 à 40 minutes jusqu’à ce que la pâte soit dorée et le centre pris.","Laisser reposer 8 minutes avant de couper; accompagner de la salade ou des herbes prévues."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, false, 'broco-chou', null, null, array['volaille']::text[], array['crème', 'poulet']::text[], array['four', 'saladier', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-enchiladas-de-poulet-gratinees-au-cheddar', 'Enchiladas de poulet gratinées au cheddar', 'Enchiladas de poulet gratinées au cheddar préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 55, 'facile', 'https://images.pexels.com/photos/31843929/pexels-photo-31843929.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Cheddar","quantity":"120","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Poulet","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Pommes de terre","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"4","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Fromage frais","quantity":"120","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préchauffer le four à 190 °C. Préparer la garniture cheddar, poulet et cuire au préalable les légumes humides dans une poêle pour évacuer leur eau.","Foncer le moule ou la plaque avec la pâte; piquer le fond. Mélanger les œufs, la crème et le fromage, puis assaisonner.","Répartir la garniture, verser l’appareil ou la sauce et enfourner 30 à 40 minutes jusqu’à ce que la pâte soit dorée et le centre pris.","Laisser reposer 8 minutes avant de couper; accompagner de la salade ou des herbes prévues."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, false, 'broco-chou', null, null, array['volaille']::text[], array['cheddar', 'poulet']::text[], array['four', 'saladier', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-brochettes-de-poulet-yakitori', 'Brochettes de poulet yakitori', 'Brochettes de poulet yakitori préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'juillet', 7, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 35, 'facile', 'https://images.pexels.com/photos/32722820/pexels-photo-32722820.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Poulet","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Poisson blanc","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Huile d''olive","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Citrons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Persil","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sécher le poisson et préparer les garnitures poulet; préchauffer le four à 190 °C si la cuisson est au four.","Cuire les accompagnements séparément: démarrer les pommes de terre ou les céréales dans une casserole d’eau salée.","Saisir le poisson dans une poêle huilée 2 à 3 min par face selon l’épaisseur, ou le cuire au four 10 à 15 min jusqu’à ce que sa chair soit opaque et se détache.","Préparer la sauce avec les aromates et le citron, puis servir immédiatement avec le poisson et l’accompagnement."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['volaille']::text[], array['poulet']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-poulet-au-beurre-de-cacahuetes-et-lait-de-coco', 'Poulet au beurre de cacahuètes et lait de coco', 'Poulet au beurre de cacahuètes et lait de coco préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 40, 'facile', 'https://images.pexels.com/photos/11381409/pexels-photo-11381409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Beurre","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Poulet","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates beurre, poulet dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['volaille']::text[], array['beurre', 'poulet']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-supreme-de-poulet-facon-cordon-bleu', 'Suprême de poulet façon cordon bleu', 'Suprême de poulet façon cordon bleu préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'février', 2, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 45, 'facile', 'https://images.pexels.com/photos/12349437/pexels-photo-12349437.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Poulet","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates poulet dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['volaille']::text[], array['poulet']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-tacos-au-poulet-avocat-et-cheddar', 'Tacos au poulet, avocat et cheddar', 'Tacos au poulet, avocat et cheddar préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 35, 'facile', 'https://images.pexels.com/photos/36498697/pexels-photo-36498697.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Avocats","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Cheddar","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Poulet","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Pain","quantity":"2","unit":"pièces","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Salade","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Tomates","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préparer les garnitures avocats, cheddar, poulet; laver et essorer les légumes, puis cuire toute protéine crue à cœur dans une poêle chaude.","Mélanger les éléments de sauce et assaisonner. Trancher le pain; le toaster ou le réchauffer à la poêle jusqu’à ce qu’il soit doré.","Monter le sandwich avec la sauce, les éléments chauds puis les légumes frais. Pour un fromage à gratiner, passer 3 à 5 minutes sous le gril.","Couper en deux et servir aussitôt, avec la garniture prévue."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['volaille']::text[], array['avocats', 'cheddar', 'poulet']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-poulet-tandoori-raita-et-naan', 'Poulet tandoori, raita et naan', 'Poulet tandoori, raita et naan préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'juin', 6, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 45, 'facile', 'https://images.pexels.com/photos/31860142/pexels-photo-31860142.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Poulet","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Pain naan","quantity":"2","unit":"pièces","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates poulet, pain naan dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['volaille']::text[], array['poulet', 'pain naan']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-cordon-bleu-de-dinde', 'Cordon bleu de dinde', 'Cordon bleu de dinde préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'février', 2, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 45, 'facile', 'https://images.pexels.com/photos/33776454/pexels-photo-33776454.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Dinde / volaille","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates dinde / volaille dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['volaille']::text[], array['dinde / volaille']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified')
ON CONFLICT (id) DO UPDATE SET
  nom = EXCLUDED.nom,
  description = EXCLUDED.description,
  saison = EXCLUDED.saison,
  mois = EXCLUDED.mois,
  mois_numero = EXCLUDED.mois_numero,
  semaine = EXCLUDED.semaine,
  jour = EXCLUDED.jour,
  tag = EXCLUDED.tag,
  categorie = EXCLUDED.categorie,
  theme_special = EXCLUDED.theme_special,
  portions = EXCLUDED.portions,
  estimated_time = EXCLUDED.estimated_time,
  difficulty = EXCLUDED.difficulty,
  image_url = EXCLUDED.image_url,
  ingredients = EXCLUDED.ingredients,
  instructions = EXCLUDED.instructions,
  astuce = EXCLUDED.astuce,
  cuisson_micro_ondes = EXCLUDED.cuisson_micro_ondes,
  sans_four = EXCLUDED.sans_four,
  source = EXCLUDED.source,
  source_pdf = EXCLUDED.source_pdf,
  source_page = EXCLUDED.source_page,
  dietary_tags = EXCLUDED.dietary_tags,
  main_ingredients = EXCLUDED.main_ingredients,
  equipment = EXCLUDED.equipment,
  canonical_ingredients_status = EXCLUDED.canonical_ingredients_status;

-- Keep ingredient JSON category labels aligned with the canonical ingredient catalog.
UPDATE public.recipes AS recipe
SET ingredients = (
  SELECT jsonb_agg(jsonb_set(item.ingredient, '{category}', to_jsonb(canonical.category), true) ORDER BY item.ordinality)
  FROM jsonb_array_elements(recipe.ingredients) WITH ORDINALITY AS item(ingredient, ordinality)
  JOIN public.ingredients AS canonical ON canonical.name = item.ingredient->>'name'
)
WHERE recipe.id IN ('city-cafe-supreme-de-poulet-roti-sauce-aux-morilles', 'city-cafe-tenders-de-poulet-et-sauce-cajun', 'city-cafe-supreme-de-poulet-roti-jus-creme-et-gratin-dauphinois', 'city-cafe-enchiladas-de-poulet-gratinees-au-cheddar', 'city-cafe-brochettes-de-poulet-yakitori', 'city-cafe-poulet-au-beurre-de-cacahuetes-et-lait-de-coco', 'city-cafe-supreme-de-poulet-facon-cordon-bleu', 'city-cafe-tacos-au-poulet-avocat-et-cheddar', 'city-cafe-poulet-tandoori-raita-et-naan', 'city-cafe-cordon-bleu-de-dinde');

-- Keep recipe image choices in sync if reviewed later.
UPDATE public.recipes AS recipe
SET image_url = image.image_url
FROM (VALUES
  ('city-cafe-supreme-de-poulet-roti-sauce-aux-morilles', 'https://images.pexels.com/photos/36863872/pexels-photo-36863872.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-tenders-de-poulet-et-sauce-cajun', 'https://images.pexels.com/photos/8859016/pexels-photo-8859016.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-supreme-de-poulet-roti-jus-creme-et-gratin-dauphinois', 'https://images.pexels.com/photos/20150680/pexels-photo-20150680.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-enchiladas-de-poulet-gratinees-au-cheddar', 'https://images.pexels.com/photos/31843929/pexels-photo-31843929.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-brochettes-de-poulet-yakitori', 'https://images.pexels.com/photos/32722820/pexels-photo-32722820.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-poulet-au-beurre-de-cacahuetes-et-lait-de-coco', 'https://images.pexels.com/photos/11381409/pexels-photo-11381409.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-supreme-de-poulet-facon-cordon-bleu', 'https://images.pexels.com/photos/12349437/pexels-photo-12349437.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-tacos-au-poulet-avocat-et-cheddar', 'https://images.pexels.com/photos/36498697/pexels-photo-36498697.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-poulet-tandoori-raita-et-naan', 'https://images.pexels.com/photos/31860142/pexels-photo-31860142.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-cordon-bleu-de-dinde', 'https://images.pexels.com/photos/33776454/pexels-photo-33776454.jpeg?auto=compress&cs=tinysrgb&h=650&w=940')
) AS image(id, image_url)
WHERE recipe.id = image.id;

COMMIT;
