-- City Café batch 07: recettes. Generated from city-cafe-recipes-batch-07.json.
BEGIN;

INSERT INTO public.ingredients (name, category, aliases)
VALUES
  ('Bœuf', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Oignons', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Carottes', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Ail', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Bouillon', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Thym', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Sel et poivre', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Moutarde', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Haricots rouges', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Pâtes', 'Féculents, pains et céréales', '{}'::text[]),
  ('Huile d''olive', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Semoule', 'Féculents, pains et céréales', '{}'::text[]),
  ('Pruneaux', 'Fruits, légumes et légumineuses', '{}'::text[])
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.recipes (id, nom, description, saison, mois, mois_numero, semaine, jour, tag, categorie, theme_special, portions, estimated_time, difficulty, image_url, ingredients, instructions, astuce, cuisson_micro_ondes, sans_four, source, source_pdf, source_page, dietary_tags, main_ingredients, equipment, canonical_ingredients_status)
VALUES
  ('city-cafe-joue-de-boeuf-mijotee', 'Joue de bœuf mijotée', 'Joue de bœuf mijotée préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 210, 'intermédiaire', 'https://images.pexels.com/photos/8112923/pexels-photo-8112923.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Bœuf","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['bœuf']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-boeuf-bourguignon-a-l-ancienne-et-pommes-de-terre-vapeur', 'Bœuf bourguignon à l’ancienne et pommes de terre vapeur', 'Bœuf bourguignon à l’ancienne et pommes de terre vapeur préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 210, 'intermédiaire', 'https://images.pexels.com/photos/22711494/pexels-photo-22711494.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Bœuf","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['bœuf']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-tartare-de-boeuf-a-l-italienne', 'Tartare de bœuf à l’italienne', 'Tartare de bœuf à l’italienne préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'juillet', 7, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 25, 'très facile', 'https://images.pexels.com/photos/13806702/pexels-photo-13806702.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Bœuf","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Choisir chez un boucher de confiance un morceau entier très frais destiné à être consommé cru; le garder à 4 °C ou moins et préparer tout juste avant le repas.","Nettoyer soigneusement planche et couteau. Parer le bœuf puis le hacher au couteau juste avant de servir; ne pas utiliser de viande hachée déjà préparée.","Incorporer huile d’olive, câpres, parmesan râpé, moutarde et jaune d’œuf pasteurisé si souhaité. Le citron parfume mais ne rend pas la viande crue sûre.","Dresser immédiatement, servir sans attendre et jeter tout reste resté à température ambiante."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['bœuf']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-aiguillette-baronne-de-boeuf-hollandaise-a-la-moutarde', 'Aiguillette baronne de bœuf, hollandaise à la moutarde', 'Aiguillette baronne de bœuf, hollandaise à la moutarde préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'printemps', 'mai', 5, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 40, 'facile', 'https://images.pexels.com/photos/19396435/pexels-photo-19396435.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Bœuf","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Moutarde","quantity":"150","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates bœuf, moutarde dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['bœuf', 'moutarde']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-mafe-de-boeuf-et-haricots-rouges', 'Mafé de bœuf et haricots rouges', 'Mafé de bœuf et haricots rouges préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 120, 'intermédiaire', 'https://images.pexels.com/photos/36430151/pexels-photo-36430151.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Bœuf","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Haricots rouges","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['bœuf', 'haricots rouges']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-langue-de-boeuf-confite-et-sauce-gribiche', 'Langue de bœuf confite et sauce gribiche', 'Langue de bœuf confite et sauce gribiche préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 210, 'intermédiaire', 'https://images.pexels.com/photos/15997561/pexels-photo-15997561.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Bœuf","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['bœuf']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-ragout-de-boeuf-du-mezzogiorno', 'Ragoût de bœuf du Mezzogiorno', 'Ragoût de bœuf du Mezzogiorno préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'février', 2, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 180, 'intermédiaire', 'https://images.pexels.com/photos/17237175/pexels-photo-17237175.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Bœuf","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['bœuf']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-lasagnes-de-boeuf', 'Lasagnes de bœuf', 'Lasagnes de bœuf préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 90, 'facile', 'https://images.pexels.com/photos/5949900/pexels-photo-5949900.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Bœuf","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Pâtes","quantity":"320","unit":"g secs","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Huile d''olive","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Porter une grande casserole d’eau salée à ébullition et cuire les pâtes selon leur emballage; réserver une louche d’eau de cuisson.","Pendant ce temps, préparer et couper les garnitures bœuf. Faire revenir les éléments aromatiques dans une poêle avec l’huile.","Ajouter les ingrédients principaux et cuire jusqu’à tendreté; incorporer la sauce ou le fromage prévu et détendre avec un peu d’eau de cuisson.","Mélanger avec les pâtes égouttées, rectifier l’assaisonnement et servir aussitôt avec la garniture restante."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['bœuf']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-tajine-de-jarret-de-boeuf-aux-pruneaux-et-semoule', 'Tajine de jarret de bœuf aux pruneaux et semoule', 'Tajine de jarret de bœuf aux pruneaux et semoule préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'février', 2, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 210, 'intermédiaire', 'https://images.pexels.com/photos/23025176/pexels-photo-23025176.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Semoule","quantity":"320","unit":"g secs","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Bœuf","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Pruneaux","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['semoule', 'bœuf', 'pruneaux']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-roast-beef-et-sauce-ravigote', 'Roast-beef et sauce ravigote', 'Roast-beef et sauce ravigote préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'printemps', 'mai', 5, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 70, 'facile', 'https://images.pexels.com/photos/17942032/pexels-photo-17942032.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Bœuf","quantity":"600","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sortir la viande du réfrigérateur 15 minutes avant la cuisson et l’assaisonner. Préparer les légumes et préchauffer le four à 190 °C pour les pièces à rôtir.","Faire dorer la viande dans une cocotte ou une poêle chaude avec l’huile, sur toutes ses faces; réserver si nécessaire.","Cuire les aromates bœuf dans la même matière grasse. Pour un mijoté, ajouter le bouillon, couvrir et cuire à feu doux jusqu’à ce que la viande soit tendre; pour une pièce, poursuivre au four jusqu’à cuisson à cœur adaptée.","Préparer la sauce ou les légumes d’accompagnement, laisser reposer la viande 5 à 10 minutes, puis trancher et servir."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['protéines']::text[], array['bœuf']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified')
ON CONFLICT (id) DO UPDATE SET
  nom = EXCLUDED.nom,
  description = EXCLUDED.description,
  saison = EXCLUDED.saison,
  mois = EXCLUDED.mois,
  mois_numero = EXCLUDED.mois_numero,
  semaine = EXCLUDED.semaine,
  jour = EXCLUDED.jour,
  tag = EXCLUDED.tag,
  categorie = EXCLUDED.categorie,
  theme_special = EXCLUDED.theme_special,
  portions = EXCLUDED.portions,
  estimated_time = EXCLUDED.estimated_time,
  difficulty = EXCLUDED.difficulty,
  image_url = EXCLUDED.image_url,
  ingredients = EXCLUDED.ingredients,
  instructions = EXCLUDED.instructions,
  astuce = EXCLUDED.astuce,
  cuisson_micro_ondes = EXCLUDED.cuisson_micro_ondes,
  sans_four = EXCLUDED.sans_four,
  source = EXCLUDED.source,
  source_pdf = EXCLUDED.source_pdf,
  source_page = EXCLUDED.source_page,
  dietary_tags = EXCLUDED.dietary_tags,
  main_ingredients = EXCLUDED.main_ingredients,
  equipment = EXCLUDED.equipment,
  canonical_ingredients_status = EXCLUDED.canonical_ingredients_status;

-- Keep ingredient JSON category labels aligned with the canonical ingredient catalog.
UPDATE public.recipes AS recipe
SET ingredients = (
  SELECT jsonb_agg(jsonb_set(item.ingredient, '{category}', to_jsonb(canonical.category), true) ORDER BY item.ordinality)
  FROM jsonb_array_elements(recipe.ingredients) WITH ORDINALITY AS item(ingredient, ordinality)
  JOIN public.ingredients AS canonical ON canonical.name = item.ingredient->>'name'
)
WHERE recipe.id IN ('city-cafe-joue-de-boeuf-mijotee', 'city-cafe-boeuf-bourguignon-a-l-ancienne-et-pommes-de-terre-vapeur', 'city-cafe-tartare-de-boeuf-a-l-italienne', 'city-cafe-aiguillette-baronne-de-boeuf-hollandaise-a-la-moutarde', 'city-cafe-mafe-de-boeuf-et-haricots-rouges', 'city-cafe-langue-de-boeuf-confite-et-sauce-gribiche', 'city-cafe-ragout-de-boeuf-du-mezzogiorno', 'city-cafe-lasagnes-de-boeuf', 'city-cafe-tajine-de-jarret-de-boeuf-aux-pruneaux-et-semoule', 'city-cafe-roast-beef-et-sauce-ravigote');

-- Keep recipe image choices in sync if reviewed later.
UPDATE public.recipes AS recipe
SET image_url = image.image_url
FROM (VALUES
  ('city-cafe-joue-de-boeuf-mijotee', 'https://images.pexels.com/photos/8112923/pexels-photo-8112923.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-boeuf-bourguignon-a-l-ancienne-et-pommes-de-terre-vapeur', 'https://images.pexels.com/photos/22711494/pexels-photo-22711494.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-tartare-de-boeuf-a-l-italienne', 'https://images.pexels.com/photos/13806702/pexels-photo-13806702.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-aiguillette-baronne-de-boeuf-hollandaise-a-la-moutarde', 'https://images.pexels.com/photos/19396435/pexels-photo-19396435.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-mafe-de-boeuf-et-haricots-rouges', 'https://images.pexels.com/photos/36430151/pexels-photo-36430151.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-langue-de-boeuf-confite-et-sauce-gribiche', 'https://images.pexels.com/photos/15997561/pexels-photo-15997561.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-ragout-de-boeuf-du-mezzogiorno', 'https://images.pexels.com/photos/17237175/pexels-photo-17237175.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-lasagnes-de-boeuf', 'https://images.pexels.com/photos/5949900/pexels-photo-5949900.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-tajine-de-jarret-de-boeuf-aux-pruneaux-et-semoule', 'https://images.pexels.com/photos/23025176/pexels-photo-23025176.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-roast-beef-et-sauce-ravigote', 'https://images.pexels.com/photos/17942032/pexels-photo-17942032.jpeg?auto=compress&cs=tinysrgb&h=650&w=940')
) AS image(id, image_url)
WHERE recipe.id = image.id;

COMMIT;
