-- City Café batch 05: recettes. Generated from city-cafe-recipes-batch-05.json.
BEGIN;

INSERT INTO public.ingredients (name, category, aliases)
VALUES
  ('Pâte brisée', 'Féculents, pains et céréales', '{}'::text[]),
  ('Œufs', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Crème', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Sel et poivre', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Tomates', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Mozzarella', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Basilic', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Oignons', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Carottes', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Ail', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Bouillon', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Thym', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Tortillas', 'Féculents, pains et céréales', '{}'::text[]),
  ('Beurre', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Champignons de Paris', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Brioche', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Pain', 'Féculents, pains et céréales', '{}'::text[]),
  ('Salade', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Pommes de terre', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Fromage frais', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Épinards', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Noix de muscade', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Butternut', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Mayonnaise', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Avocats', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Feta', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Zaatar', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Aubergines', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Nouilles de riz', 'Féculents, pains et céréales', '{}'::text[]),
  ('Pâtes', 'Féculents, pains et céréales', '{}'::text[]),
  ('Huile d''olive', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Cheddar', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Pois cassés', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Curry', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Riz', 'Féculents, pains et céréales', '{}'::text[]),
  ('Sésame', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Courgettes', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Pois chiches', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Blettes', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Lentilles', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Lentilles corail', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Quinoa', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Chèvre', 'Crèmerie et produits laitiers', '{}'::text[]),
  ('Saumon', 'Viandes, poissons et protéines', '{}'::text[]),
  ('Citrons', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Persil', 'Épices et herbes aromatiques', '{}'::text[]),
  ('Tahini', 'Fruits, légumes et légumineuses', '{}'::text[]),
  ('Miso', 'Épicerie, condiments et produits sucrés', '{}'::text[]),
  ('Potimarron', 'Fruits, légumes et légumineuses', '{}'::text[])
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.recipes (id, nom, description, saison, mois, mois_numero, semaine, jour, tag, categorie, theme_special, portions, estimated_time, difficulty, image_url, ingredients, instructions, astuce, cuisson_micro_ondes, sans_four, source, source_pdf, source_page, dietary_tags, main_ingredients, equipment, canonical_ingredients_status)
VALUES
  ('city-cafe-veggie-american-pot-pie', 'Veggie American Pot Pie', 'Veggie American Pot Pie préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'février', 2, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 75, 'facile', 'https://images.pexels.com/photos/39070796/pexels-photo-39070796.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâte brisée","quantity":"300","unit":"g","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Œufs","quantity":"4","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"120","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Tomates","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Mozzarella","quantity":"120","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Basilic","quantity":"300","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préchauffer le four à 190 °C. Préparer la garniture pâte brisée, œufs, crème et cuire au préalable les légumes humides dans une poêle pour évacuer leur eau.","Foncer le moule ou la plaque avec la pâte; piquer le fond. Mélanger les œufs, la crème et le fromage, puis assaisonner.","Répartir la garniture, verser l’appareil ou la sauce et enfourner 30 à 40 minutes jusqu’à ce que la pâte soit dorée et le centre pris.","Laisser reposer 8 minutes avant de couper; accompagner de la salade ou des herbes prévues."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['pâte brisée', 'œufs', 'crème']::text[], array['four', 'saladier', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-cari-d-oeufs-et-achar-de-legumes', 'Cari d’œufs et achar de légumes', 'Cari d’œufs et achar de légumes préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 40, 'facile', 'https://images.pexels.com/photos/24186308/pexels-photo-24186308.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['oignons', 'carottes', 'ail']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-omelette-espagnole-facon-tortilla', 'Omelette espagnole façon tortilla', 'Omelette espagnole façon tortilla préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'juillet', 7, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 40, 'facile', 'https://images.pexels.com/photos/21327969/pexels-photo-21327969.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Tortillas","quantity":"2","unit":"pièces","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Beurre","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préparer les légumes tortillas et les couper finement. Faire revenir les garnitures dans une poêle avec le beurre jusqu’à ce qu’elles soient tendres.","Battre les œufs avec la crème, le sel et le poivre. Verser sur la garniture chaude.","Cuire à feu doux en ramenant les bords vers le centre jusqu’à ce que l’omelette soit prise mais encore moelleuse; cuire complètement les œufs si la recette le demande.","Ajouter le fromage et les herbes, plier ou dresser les œufs et servir immédiatement."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['tortillas']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-brioche-toastee-duxelles-de-champignons-et-oeuf-au-plat', 'Brioche toastée, duxelles de champignons et œuf au plat', 'Brioche toastée, duxelles de champignons et œuf au plat préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 30, 'très facile', 'https://images.pexels.com/photos/28292002/pexels-photo-28292002.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Champignons de Paris","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Brioche","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Pain","quantity":"2","unit":"pièces","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Salade","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Tomates","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préparer les garnitures champignons de paris, œufs, brioche; laver et essorer les légumes, puis cuire toute protéine crue à cœur dans une poêle chaude.","Mélanger les éléments de sauce et assaisonner. Trancher le pain; le toaster ou le réchauffer à la poêle jusqu’à ce qu’il soit doré.","Monter le sandwich avec la sauce, les éléments chauds puis les légumes frais. Pour un fromage à gratiner, passer 3 à 5 minutes sous le gril.","Couper en deux et servir aussitôt, avec la garniture prévue."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['champignons de paris', 'œufs', 'brioche']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-croustillant-caprese', 'Croustillant caprese', 'Croustillant caprese préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 30, 'très facile', 'https://images.pexels.com/photos/18635876/pexels-photo-18635876.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pommes de terre","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Fromage frais","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Tomates","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Mozzarella","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Basilic","quantity":"150","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préchauffer le four à 190 °C. Préparer la garniture pommes de terre, œufs, fromage frais et cuire au préalable les légumes humides dans une poêle pour évacuer leur eau.","Foncer le moule ou la plaque avec la pâte; piquer le fond. Mélanger les œufs, la crème et le fromage, puis assaisonner.","Répartir la garniture, verser l’appareil ou la sauce et enfourner 30 à 40 minutes jusqu’à ce que la pâte soit dorée et le centre pris.","Laisser reposer 8 minutes avant de couper; accompagner de la salade ou des herbes prévues."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['pommes de terre', 'œufs', 'fromage frais']::text[], array['four', 'saladier', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-huevos-rancheros-et-salsa-verde', 'Huevos rancheros et salsa verde', 'Huevos rancheros et salsa verde préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 40, 'facile', 'https://images.pexels.com/photos/31823016/pexels-photo-31823016.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Beurre","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Épinards","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Fromage frais","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Noix de muscade","quantity":"150","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préparer les légumes œufs, beurre, crème et les couper finement. Faire revenir les garnitures dans une poêle avec le beurre jusqu’à ce qu’elles soient tendres.","Battre les œufs avec la crème, le sel et le poivre. Verser sur la garniture chaude.","Cuire à feu doux en ramenant les bords vers le centre jusqu’à ce que l’omelette soit prise mais encore moelleuse; cuire complètement les œufs si la recette le demande.","Ajouter le fromage et les herbes, plier ou dresser les œufs et servir immédiatement."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['œufs', 'beurre', 'crème']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-omelette-a-la-courge-aux-champignons-et-au-fromage-frais', 'Omelette à la courge, aux champignons et au fromage frais', 'Omelette à la courge, aux champignons et au fromage frais préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 35, 'facile', 'https://images.pexels.com/photos/27359373/pexels-photo-27359373.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Butternut","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Champignons de Paris","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Beurre","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préparer les légumes butternut, champignons de paris et les couper finement. Faire revenir les garnitures dans une poêle avec le beurre jusqu’à ce qu’elles soient tendres.","Battre les œufs avec la crème, le sel et le poivre. Verser sur la garniture chaude.","Cuire à feu doux en ramenant les bords vers le centre jusqu’à ce que l’omelette soit prise mais encore moelleuse; cuire complètement les œufs si la recette le demande.","Ajouter le fromage et les herbes, plier ou dresser les œufs et servir immédiatement."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['butternut', 'champignons de paris']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-gua-bao-au-tofu-et-legumes-croquants', 'Gua bao au tofu et légumes croquants', 'Gua bao au tofu et légumes croquants préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'juin', 6, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 40, 'facile', 'https://images.pexels.com/photos/14855134/pexels-photo-14855134.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pain","quantity":"2","unit":"pièces","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Salade","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Tomates","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Mozzarella","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Basilic","quantity":"150","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Mayonnaise","quantity":"150","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préparer les garnitures pain, salade, tomates; laver et essorer les légumes, puis cuire toute protéine crue à cœur dans une poêle chaude.","Mélanger les éléments de sauce et assaisonner. Trancher le pain; le toaster ou le réchauffer à la poêle jusqu’à ce qu’il soit doré.","Monter le sandwich avec la sauce, les éléments chauds puis les légumes frais. Pour un fromage à gratiner, passer 3 à 5 minutes sous le gril.","Couper en deux et servir aussitôt, avec la garniture prévue."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['pain', 'salade', 'tomates']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-oeufs-a-la-florentine', 'Œufs à la florentine', 'Œufs à la florentine préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'printemps', 'avril', 4, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 35, 'facile', 'https://images.pexels.com/photos/12268531/pexels-photo-12268531.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Beurre","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Épinards","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Fromage frais","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Noix de muscade","quantity":"150","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Préparer les légumes œufs, beurre, crème et les couper finement. Faire revenir les garnitures dans une poêle avec le beurre jusqu’à ce qu’elles soient tendres.","Battre les œufs avec la crème, le sel et le poivre. Verser sur la garniture chaude.","Cuire à feu doux en ramenant les bords vers le centre jusqu’à ce que l’omelette soit prise mais encore moelleuse; cuire complètement les œufs si la recette le demande.","Ajouter le fromage et les herbes, plier ou dresser les œufs et servir immédiatement."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['œufs', 'beurre', 'crème']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-tartine-a-l-avocat-tomate-mozzarella-et-sauce-vierge', 'Tartine à l’avocat, tomate, mozzarella et sauce vierge', 'Tartine à l’avocat, tomate, mozzarella et sauce vierge préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 20, 'très facile', 'https://images.pexels.com/photos/29380178/pexels-photo-29380178.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Tomates","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Avocats","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Mozzarella","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Pain","quantity":"2","unit":"pièces","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Salade","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préparer les garnitures tomates, avocats, mozzarella; laver et essorer les légumes, puis cuire toute protéine crue à cœur dans une poêle chaude.","Mélanger les éléments de sauce et assaisonner. Trancher le pain; le toaster ou le réchauffer à la poêle jusqu’à ce qu’il soit doré.","Monter le sandwich avec la sauce, les éléments chauds puis les légumes frais. Pour un fromage à gratiner, passer 3 à 5 minutes sous le gril.","Couper en deux et servir aussitôt, avec la garniture prévue."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['tomates', 'avocats', 'mozzarella']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-croquettes-de-petits-pois-feta-et-zaatar', 'Croquettes de petits pois, feta et zaatar', 'Croquettes de petits pois, feta et zaatar préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'printemps', 'mai', 5, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 40, 'facile', 'https://images.pexels.com/photos/33217883/pexels-photo-33217883.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Feta","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Zaatar","quantity":"150","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Pommes de terre","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Fromage frais","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préchauffer le four à 190 °C. Préparer la garniture feta, zaatar et cuire au préalable les légumes humides dans une poêle pour évacuer leur eau.","Foncer le moule ou la plaque avec la pâte; piquer le fond. Mélanger les œufs, la crème et le fromage, puis assaisonner.","Répartir la garniture, verser l’appareil ou la sauce et enfourner 30 à 40 minutes jusqu’à ce que la pâte soit dorée et le centre pris.","Laisser reposer 8 minutes avant de couper; accompagner de la salade ou des herbes prévues."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['feta', 'zaatar']::text[], array['four', 'saladier', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-brioche-perdue-salee-caviar-d-aubergine-et-oeuf-au-plat', 'Brioche perdue salée, caviar d’aubergine et œuf au plat', 'Brioche perdue salée, caviar d’aubergine et œuf au plat préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 35, 'facile', 'https://images.pexels.com/photos/26586541/pexels-photo-26586541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Aubergines","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Brioche","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Beurre","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préparer les légumes aubergines, œufs, brioche et les couper finement. Faire revenir les garnitures dans une poêle avec le beurre jusqu’à ce qu’elles soient tendres.","Battre les œufs avec la crème, le sel et le poivre. Verser sur la garniture chaude.","Cuire à feu doux en ramenant les bords vers le centre jusqu’à ce que l’omelette soit prise mais encore moelleuse; cuire complètement les œufs si la recette le demande.","Ajouter le fromage et les herbes, plier ou dresser les œufs et servir immédiatement."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['aubergines', 'œufs', 'brioche']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-nouilles-sautees-aux-legumes-d-ete', 'Nouilles sautées aux légumes d’été', 'Nouilles sautées aux légumes d’été préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'août', 8, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 30, 'très facile', 'https://images.pexels.com/photos/8935245/pexels-photo-8935245.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Nouilles de riz","quantity":"160","unit":"g secs","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Pâtes","quantity":"160","unit":"g secs","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Huile d''olive","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Porter une grande casserole d’eau salée à ébullition et cuire les pâtes selon leur emballage; réserver une louche d’eau de cuisson.","Pendant ce temps, préparer et couper les garnitures nouilles de riz. Faire revenir les éléments aromatiques dans une poêle avec l’huile.","Ajouter les ingrédients principaux et cuire jusqu’à tendreté; incorporer la sauce ou le fromage prévu et détendre avec un peu d’eau de cuisson.","Mélanger avec les pâtes égouttées, rectifier l’assaisonnement et servir aussitôt avec la garniture restante."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['nouilles de riz']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-pain-croustillant-gratine-au-cheddar', 'Pain croustillant gratiné au cheddar', 'Pain croustillant gratiné au cheddar préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 20, 'très facile', 'https://images.pexels.com/photos/33042510/pexels-photo-33042510.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Cheddar","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Pain","quantity":"2","unit":"pièces","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Pommes de terre","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Fromage frais","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préchauffer le four à 190 °C. Préparer la garniture cheddar, pain et cuire au préalable les légumes humides dans une poêle pour évacuer leur eau.","Foncer le moule ou la plaque avec la pâte; piquer le fond. Mélanger les œufs, la crème et le fromage, puis assaisonner.","Répartir la garniture, verser l’appareil ou la sauce et enfourner 30 à 40 minutes jusqu’à ce que la pâte soit dorée et le centre pris.","Laisser reposer 8 minutes avant de couper; accompagner de la salade ou des herbes prévues."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, false, 'broco-chou', null, null, array['végétarien']::text[], array['cheddar', 'pain']::text[], array['four', 'saladier', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-curry-de-pois-casses-epinards-et-patate-douce-oeuf-au-plat', 'Curry de pois cassés, épinards et patate douce, œuf au plat', 'Curry de pois cassés, épinards et patate douce, œuf au plat préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 65, 'facile', 'https://images.pexels.com/photos/9213999/pexels-photo-9213999.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Épinards","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Pois cassés","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Curry","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['épinards', 'pois cassés', 'œufs', 'curry']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-chou-fleur-caramelise-au-sesame-et-riz-a-sushi', 'Chou-fleur caramélisé au sésame et riz à sushi', 'Chou-fleur caramélisé au sésame et riz à sushi préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 45, 'facile', 'https://images.pexels.com/photos/9213991/pexels-photo-9213991.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Riz","quantity":"160","unit":"g secs","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Sésame","quantity":"150","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Huile d''olive","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préparer et couper les légumes riz, sésame en morceaux réguliers. Préchauffer le four à 200 °C si la recette prévoit une cuisson rôtie.","Faire revenir les aromates dans une casserole ou une grande poêle avec l’huile, puis ajouter les légumes et les légumineuses.","Ajouter un fond d’eau ou de bouillon, couvrir et cuire 15 à 25 minutes jusqu’à tendreté; mélanger régulièrement et compléter le liquide si nécessaire.","Assaisonner, ajouter les herbes et le fromage prévus, puis servir avec l’accompagnement indiqué."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['riz', 'sésame']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-couscous-vegetarien-aux-saveurs-orientales', 'Couscous végétarien aux saveurs orientales', 'Couscous végétarien aux saveurs orientales préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 65, 'facile', 'https://images.pexels.com/photos/19824910/pexels-photo-19824910.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['oignons', 'carottes', 'ail']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-lasagnes-vegetariennes-automnales', 'Lasagnes végétariennes automnales', 'Lasagnes végétariennes automnales préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 75, 'facile', 'https://images.pexels.com/photos/37679127/pexels-photo-37679127.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pâtes","quantity":"320","unit":"g secs","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Huile d''olive","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Courgettes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Pois chiches","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"}]'::jsonb, '["Porter une grande casserole d’eau salée à ébullition et cuire les pâtes selon leur emballage; réserver une louche d’eau de cuisson.","Pendant ce temps, préparer et couper les garnitures pâtes, ail, huile d’olive. Faire revenir les éléments aromatiques dans une poêle avec l’huile.","Ajouter les ingrédients principaux et cuire jusqu’à tendreté; incorporer la sauce ou le fromage prévu et détendre avec un peu d’eau de cuisson.","Mélanger avec les pâtes égouttées, rectifier l’assaisonnement et servir aussitôt avec la garniture restante."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['pâtes', 'ail', 'huile d’olive']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-welsh-du-nord', 'Welsh du Nord', 'Welsh du Nord préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 25, 'très facile', 'https://images.pexels.com/photos/38169158/pexels-photo-38169158.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pain","quantity":"2","unit":"pièces","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Salade","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Tomates","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Mozzarella","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Basilic","quantity":"150","unit":"g","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Mayonnaise","quantity":"150","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préparer les garnitures pain, salade, tomates; laver et essorer les légumes, puis cuire toute protéine crue à cœur dans une poêle chaude.","Mélanger les éléments de sauce et assaisonner. Trancher le pain; le toaster ou le réchauffer à la poêle jusqu’à ce qu’il soit doré.","Monter le sandwich avec la sauce, les éléments chauds puis les légumes frais. Pour un fromage à gratiner, passer 3 à 5 minutes sous le gril.","Couper en deux et servir aussitôt, avec la garniture prévue."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['pain', 'salade', 'tomates']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-dahl-cremeux-de-lentilles-corail-courge-et-blettes', 'Dahl crémeux de lentilles corail, courge et blettes', 'Dahl crémeux de lentilles corail, courge et blettes préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 55, 'facile', 'https://images.pexels.com/photos/6544373/pexels-photo-6544373.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Butternut","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Blettes","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Lentilles","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Lentilles corail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['butternut', 'blettes', 'lentilles', 'lentilles corail']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-courge-farcie-au-quinoa-et-fromage-de-chevre', 'Courge farcie au quinoa et fromage de chèvre', 'Courge farcie au quinoa et fromage de chèvre préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 70, 'facile', 'https://images.pexels.com/photos/4899793/pexels-photo-4899793.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Butternut","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Quinoa","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Chèvre","quantity":"150","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Oignons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Huile d''olive","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préparer et couper les légumes butternut, quinoa, chèvre en morceaux réguliers. Préchauffer le four à 200 °C si la recette prévoit une cuisson rôtie.","Faire revenir les aromates dans une casserole ou une grande poêle avec l’huile, puis ajouter les légumes et les légumineuses.","Ajouter un fond d’eau ou de bouillon, couvrir et cuire 15 à 25 minutes jusqu’à tendreté; mélanger régulièrement et compléter le liquide si nécessaire.","Assaisonner, ajouter les herbes et le fromage prévus, puis servir avec l’accompagnement indiqué."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['butternut', 'quinoa', 'chèvre']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-poke-bowl-sain-au-saumon-avocat-et-legumes-croquants', 'Poke bowl sain au saumon, avocat et légumes croquants', 'Poke bowl sain au saumon, avocat et légumes croquants préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'été', 'juillet', 7, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 35, 'facile', 'https://images.pexels.com/photos/36555140/pexels-photo-36555140.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Avocats","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Saumon","quantity":"300","unit":"g","canonical":true,"category":"Viandes, poissons et protéines"},{"name":"Huile d''olive","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Citrons","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Persil","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Sécher le poisson et préparer les garnitures avocats, saumon; préchauffer le four à 190 °C si la cuisson est au four.","Cuire les accompagnements séparément: démarrer les pommes de terre ou les céréales dans une casserole d’eau salée.","Saisir le poisson dans une poêle huilée 2 à 3 min par face selon l’épaisseur, ou le cuire au four 10 à 15 min jusqu’à ce que sa chair soit opaque et se détache.","Préparer la sauce avec les aromates et le citron, puis servir immédiatement avec le poisson et l’accompagnement."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['poisson']::text[], array['avocats', 'saumon']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-tajine-vert-de-legumes-et-pois-chiches', 'Tajine vert de légumes et pois chiches', 'Tajine vert de légumes et pois chiches préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'printemps', 'mai', 5, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 70, 'facile', 'https://images.pexels.com/photos/998244/pexels-photo-998244.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Pois chiches","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Oignons","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Carottes","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Bouillon","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Thym","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épices et herbes aromatiques"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Éplucher et couper les oignons et les carottes en morceaux réguliers; sécher et assaisonner la viande si le plat en contient. Faire chauffer l’huile dans une cocotte.","Faire dorer la viande par petites quantités, puis ajouter oignons, carottes et ail et cuire 4 minutes. Pour une version végétarienne, faire simplement revenir les légumes et les légumineuses.","Ajouter le bouillon et les aromates, couvrir et mijoter doucement jusqu’à ce que les ingrédients soient tendres (30 à 90 minutes selon le plat); remuer et ajouter un peu d’eau si nécessaire.","Cuire l’accompagnement séparément, goûter la sauce, rectifier l’assaisonnement et servir chaud."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['pois chiches']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-patate-douce-farcie-a-la-duxelles-de-champignons-et-oeuf-mollet', 'Patate douce farcie à la duxelles de champignons et œuf mollet', 'Patate douce farcie à la duxelles de champignons et œuf mollet préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 65, 'facile', 'https://images.pexels.com/photos/35546716/pexels-photo-35546716.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Champignons de Paris","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Œufs","quantity":"2","unit":"pièces","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Beurre","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Crème","quantity":"60","unit":"g","canonical":true,"category":"Crèmerie et produits laitiers"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Préparer les légumes champignons de paris, œufs et les couper finement. Faire revenir les garnitures dans une poêle avec le beurre jusqu’à ce qu’elles soient tendres.","Battre les œufs avec la crème, le sel et le poivre. Verser sur la garniture chaude.","Cuire à feu doux en ramenant les bords vers le centre jusqu’à ce que l’omelette soit prise mais encore moelleuse; cuire complètement les œufs si la recette le demande.","Ajouter le fromage et les herbes, plier ou dresser les œufs et servir immédiatement."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['champignons de paris', 'œufs']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-ramen-vegetarien-au-miso-et-tahini', 'Ramen végétarien au miso et tahini', 'Ramen végétarien au miso et tahini préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'hiver', 'janvier', 1, null, null, 'déjeuner/dîner', 'salé', null, '2 personnes', 40, 'facile', 'https://images.pexels.com/photos/4224212/pexels-photo-4224212.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Tahini","quantity":"150","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Miso","quantity":"150","unit":"g","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Pâtes","quantity":"160","unit":"g secs","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Ail","quantity":"1","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Huile d''olive","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Porter une grande casserole d’eau salée à ébullition et cuire les pâtes selon leur emballage; réserver une louche d’eau de cuisson.","Pendant ce temps, préparer et couper les garnitures tahini, miso. Faire revenir les éléments aromatiques dans une poêle avec l’huile.","Ajouter les ingrédients principaux et cuire jusqu’à tendreté; incorporer la sauce ou le fromage prévu et détendre avec un peu d’eau de cuisson.","Mélanger avec les pâtes égouttées, rectifier l’assaisonnement et servir aussitôt avec la garniture restante."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['tahini', 'miso']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified'),
  ('city-cafe-lasagnes-gourmandes-au-potimarron-et-a-la-roquette', 'Lasagnes gourmandes au potimarron et à la roquette', 'Lasagnes gourmandes au potimarron et à la roquette préparé simplement à la maison, avec des quantités équilibrées et une cuisson adaptée aux ingrédients.', 'automne', 'octobre', 10, null, null, 'déjeuner/dîner', 'salé', null, '4 personnes', 75, 'facile', 'https://images.pexels.com/photos/31119078/pexels-photo-31119078.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', '[{"name":"Potimarron","quantity":"300","unit":"g","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Pâtes","quantity":"320","unit":"g secs","canonical":true,"category":"Féculents, pains et céréales"},{"name":"Ail","quantity":"2","unit":"pièces","canonical":true,"category":"Fruits, légumes et légumineuses"},{"name":"Huile d''olive","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"},{"name":"Sel et poivre","quantity":"1","unit":"c. à soupe","canonical":true,"category":"Épicerie, condiments et produits sucrés"}]'::jsonb, '["Porter une grande casserole d’eau salée à ébullition et cuire les pâtes selon leur emballage; réserver une louche d’eau de cuisson.","Pendant ce temps, préparer et couper les garnitures potimarron. Faire revenir les éléments aromatiques dans une poêle avec l’huile.","Ajouter les ingrédients principaux et cuire jusqu’à tendreté; incorporer la sauce ou le fromage prévu et détendre avec un peu d’eau de cuisson.","Mélanger avec les pâtes égouttées, rectifier l’assaisonnement et servir aussitôt avec la garniture restante."]'::jsonb, 'Préparez et pesez les ingrédients avant de commencer; ajustez le temps de cuisson à la taille réelle des morceaux et vérifiez la cuisson avant de servir.', false, true, 'broco-chou', null, null, array['végétarien']::text[], array['potimarron']::text[], array['casserole', 'poêle', 'couteau', 'planche à découper']::text[], 'verified')
ON CONFLICT (id) DO UPDATE SET
  nom = EXCLUDED.nom,
  description = EXCLUDED.description,
  saison = EXCLUDED.saison,
  mois = EXCLUDED.mois,
  mois_numero = EXCLUDED.mois_numero,
  semaine = EXCLUDED.semaine,
  jour = EXCLUDED.jour,
  tag = EXCLUDED.tag,
  categorie = EXCLUDED.categorie,
  theme_special = EXCLUDED.theme_special,
  portions = EXCLUDED.portions,
  estimated_time = EXCLUDED.estimated_time,
  difficulty = EXCLUDED.difficulty,
  image_url = EXCLUDED.image_url,
  ingredients = EXCLUDED.ingredients,
  instructions = EXCLUDED.instructions,
  astuce = EXCLUDED.astuce,
  cuisson_micro_ondes = EXCLUDED.cuisson_micro_ondes,
  sans_four = EXCLUDED.sans_four,
  source = EXCLUDED.source,
  source_pdf = EXCLUDED.source_pdf,
  source_page = EXCLUDED.source_page,
  dietary_tags = EXCLUDED.dietary_tags,
  main_ingredients = EXCLUDED.main_ingredients,
  equipment = EXCLUDED.equipment,
  canonical_ingredients_status = EXCLUDED.canonical_ingredients_status;

-- Keep ingredient JSON category labels aligned with the canonical ingredient catalog.
UPDATE public.recipes AS recipe
SET ingredients = (
  SELECT jsonb_agg(jsonb_set(item.ingredient, '{category}', to_jsonb(canonical.category), true) ORDER BY item.ordinality)
  FROM jsonb_array_elements(recipe.ingredients) WITH ORDINALITY AS item(ingredient, ordinality)
  JOIN public.ingredients AS canonical ON canonical.name = item.ingredient->>'name'
)
WHERE recipe.id IN ('city-cafe-veggie-american-pot-pie', 'city-cafe-cari-d-oeufs-et-achar-de-legumes', 'city-cafe-omelette-espagnole-facon-tortilla', 'city-cafe-brioche-toastee-duxelles-de-champignons-et-oeuf-au-plat', 'city-cafe-croustillant-caprese', 'city-cafe-huevos-rancheros-et-salsa-verde', 'city-cafe-omelette-a-la-courge-aux-champignons-et-au-fromage-frais', 'city-cafe-gua-bao-au-tofu-et-legumes-croquants', 'city-cafe-oeufs-a-la-florentine', 'city-cafe-tartine-a-l-avocat-tomate-mozzarella-et-sauce-vierge', 'city-cafe-croquettes-de-petits-pois-feta-et-zaatar', 'city-cafe-brioche-perdue-salee-caviar-d-aubergine-et-oeuf-au-plat', 'city-cafe-nouilles-sautees-aux-legumes-d-ete', 'city-cafe-pain-croustillant-gratine-au-cheddar', 'city-cafe-curry-de-pois-casses-epinards-et-patate-douce-oeuf-au-plat', 'city-cafe-chou-fleur-caramelise-au-sesame-et-riz-a-sushi', 'city-cafe-couscous-vegetarien-aux-saveurs-orientales', 'city-cafe-lasagnes-vegetariennes-automnales', 'city-cafe-welsh-du-nord', 'city-cafe-dahl-cremeux-de-lentilles-corail-courge-et-blettes', 'city-cafe-courge-farcie-au-quinoa-et-fromage-de-chevre', 'city-cafe-poke-bowl-sain-au-saumon-avocat-et-legumes-croquants', 'city-cafe-tajine-vert-de-legumes-et-pois-chiches', 'city-cafe-patate-douce-farcie-a-la-duxelles-de-champignons-et-oeuf-mollet', 'city-cafe-ramen-vegetarien-au-miso-et-tahini', 'city-cafe-lasagnes-gourmandes-au-potimarron-et-a-la-roquette');

-- Keep recipe image choices in sync if reviewed later.
UPDATE public.recipes AS recipe
SET image_url = image.image_url
FROM (VALUES
  ('city-cafe-veggie-american-pot-pie', 'https://images.pexels.com/photos/39070796/pexels-photo-39070796.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-cari-d-oeufs-et-achar-de-legumes', 'https://images.pexels.com/photos/24186308/pexels-photo-24186308.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-omelette-espagnole-facon-tortilla', 'https://images.pexels.com/photos/21327969/pexels-photo-21327969.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-brioche-toastee-duxelles-de-champignons-et-oeuf-au-plat', 'https://images.pexels.com/photos/28292002/pexels-photo-28292002.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-croustillant-caprese', 'https://images.pexels.com/photos/18635876/pexels-photo-18635876.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-huevos-rancheros-et-salsa-verde', 'https://images.pexels.com/photos/31823016/pexels-photo-31823016.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-omelette-a-la-courge-aux-champignons-et-au-fromage-frais', 'https://images.pexels.com/photos/27359373/pexels-photo-27359373.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-gua-bao-au-tofu-et-legumes-croquants', 'https://images.pexels.com/photos/14855134/pexels-photo-14855134.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-oeufs-a-la-florentine', 'https://images.pexels.com/photos/12268531/pexels-photo-12268531.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-tartine-a-l-avocat-tomate-mozzarella-et-sauce-vierge', 'https://images.pexels.com/photos/29380178/pexels-photo-29380178.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-croquettes-de-petits-pois-feta-et-zaatar', 'https://images.pexels.com/photos/33217883/pexels-photo-33217883.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-brioche-perdue-salee-caviar-d-aubergine-et-oeuf-au-plat', 'https://images.pexels.com/photos/26586541/pexels-photo-26586541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-nouilles-sautees-aux-legumes-d-ete', 'https://images.pexels.com/photos/8935245/pexels-photo-8935245.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-pain-croustillant-gratine-au-cheddar', 'https://images.pexels.com/photos/33042510/pexels-photo-33042510.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-curry-de-pois-casses-epinards-et-patate-douce-oeuf-au-plat', 'https://images.pexels.com/photos/9213999/pexels-photo-9213999.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-chou-fleur-caramelise-au-sesame-et-riz-a-sushi', 'https://images.pexels.com/photos/9213991/pexels-photo-9213991.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-couscous-vegetarien-aux-saveurs-orientales', 'https://images.pexels.com/photos/19824910/pexels-photo-19824910.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-lasagnes-vegetariennes-automnales', 'https://images.pexels.com/photos/37679127/pexels-photo-37679127.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-welsh-du-nord', 'https://images.pexels.com/photos/38169158/pexels-photo-38169158.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-dahl-cremeux-de-lentilles-corail-courge-et-blettes', 'https://images.pexels.com/photos/6544373/pexels-photo-6544373.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-courge-farcie-au-quinoa-et-fromage-de-chevre', 'https://images.pexels.com/photos/4899793/pexels-photo-4899793.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-poke-bowl-sain-au-saumon-avocat-et-legumes-croquants', 'https://images.pexels.com/photos/36555140/pexels-photo-36555140.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-tajine-vert-de-legumes-et-pois-chiches', 'https://images.pexels.com/photos/998244/pexels-photo-998244.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-patate-douce-farcie-a-la-duxelles-de-champignons-et-oeuf-mollet', 'https://images.pexels.com/photos/35546716/pexels-photo-35546716.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-ramen-vegetarien-au-miso-et-tahini', 'https://images.pexels.com/photos/4224212/pexels-photo-4224212.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'),
  ('city-cafe-lasagnes-gourmandes-au-potimarron-et-a-la-roquette', 'https://images.pexels.com/photos/31119078/pexels-photo-31119078.jpeg?auto=compress&cs=tinysrgb&h=650&w=940')
) AS image(id, image_url)
WHERE recipe.id = image.id;

COMMIT;
